### ISSUE TITLE
engine.range undefined

### ISSUE THREAD

**Issue by milhaus** [Hacksore/bluelinky#106]
**Describe the bug**
VehicleStatus engine.range is undefined. It always returns this value for me. None of the other values in the payload are undefined. Vehicle is a US 2021 Kona EV.

**Usefull info(please complete the following information):**
 - OS: Linux Debian Buster
 - Bluelinky Version 6.0.0
 - Region: US

**Additional context**
Snip from update payload:

```
engine: {
    ignition: false,
    adaptiveCruiseControl: false,
    range: undefined,
    charging: false,
    batteryCharge12v: 85,
    batteryChargeHV: 85
  }
```

I don't really know how to instrument this to get raw response data as I'm using bluelinky as an end-user of another project. More info in https://github.com/athal7/homebridge-hyundai-bluelink/issues/7

**Comment by milhaus** [comment]
Oops: npm -v bluelinky reported npm's version, not bluelinky. I don't know what version of bluelinky is bundled, but I can say I installed the package that embeds it for the first time a couple weeks ago.

**Comment by Hacksore** [comment]
This is basically because the US doesn't handle the EV's status parsing well.

@milhaus Would you be able to post a raw status output from your EV to better help me build the mapping.

**Comment by milhaus** [comment]
Sorry to leave you hanging... I've got a newborn on my hands. I tried getting a script together with the bluelinky instance installed as a dependency of homebridge-hyundai-bluelink but it looks like it'll be easier to set up a dedicated VM to capture the raw status. Maybe there's a bluelinky docker out there that could speed things up?

**Comment by Hacksore** [comment]
@milhaus yeah, I have one that needs to be updated :)

https://github.com/Hacksore/bluelinky-docker

**Comment by milhaus** [comment]
I was able to get things running in a VM and run the debug script. The raw status options under "what you wanna do" err'd out as undefined, but I was able to get responses from status on server cache:

Here's a snip from "status (on server cache)". Note there is no range under engine:

`"engine": {
    "ignition": false,
    "accessory": false,
    "charging": false,
    "batteryCharge12v": 82,
    "batteryChargeHV": 100
  }`

And here's the status object from "status (on server cache) unparsed". Note that engine is false:

`status : {
  "dateTime": "2021-04-03T19:58:29Z",
  "acc": false,
  "trunkOpen": false,
  "doorLock": true,
  "defrostStatus": "false",
  "transCond": true,
  "doorLockStatus": "true",
  "doorOpen": {
    "frontRight": 0,
    "frontLeft": 0,
    "backLeft": 0,
    "backRight": 0
  },
  "airCtrlOn": false,
  "airTemp": {
    "unit": 1,
    "hvacTempType": 1,
    "value": "LO"
  },
  "evStatus": {
    "valueDiff": 0,
    "remainTime2": {
      "etc3": {
        "unit": 1,
        "value": 0
      },
      "etc2": {
        "unit": 1,
        "value": 0
      },
      "atc": {
        "unit": 1,
        "value": 0
      },
      "etc1": {
        "unit": 1,
        "value": 0
      }
    },
    "evIgnitionStatus": true,
    "batteryPlugin": 0,
    "timeDiff": 20415,
    "batteryCharge": false,
    "batteryStatus": 100,
    "remainTime": [],
    "drvDistance": [
      {
        "rangeByFuel": {
          "gasModeRange": {
            "unit": 3,
            "value": 0
          },
          "totalAvailableRange": {
            "unit": 3,
            "value": 294
          },
          "evModeRange": {
            "unit": 3,
            "value": 294
          }
        },
        "type": 2
      }
    ],
    "reservChargeInfos": {
      "targetSOClist": [
        {
          "rangeByFuel": {
            "gasModeRange": {
              "unit": 3,
              "value": 0
            },
            "totalAvailableRange": {
              "unit": 3,
              "value": 294
            },
            "evModeRange": {
              "unit": 3,
              "value": 294
            }
          },
          "plugType": 0,
          "targetSOClevel": 100,
          "type": 2
        },
        {
          "rangeByFuel": {
            "gasModeRange": {
              "unit": 3,
              "value": 0
            },
            "totalAvailableRange": {
              "unit": 3,
              "value": 294
            },
            "evModeRange": {
              "unit": 3,
              "value": 294
            }
          },
          "plugType": 1,
          "targetSOClevel": 100,
          "type": 2
        }
      ],
      "reservChargeInfo": {
        "dateTime": "2021/04/03T14:16:58Z",
        "reservChargeInfoDetail": {
          "reservChargeSet": false,
          "reservEndTime": "",
          "reservFatcSet": {
            "defrost": false,
            "airTemp": {
              "unit": 1,
              "value": "75"
            },
            "airCtrl": 0
          },
          "reservInfo": {
            "time": {
              "timeSection": 0,
              "time": "1200"
            },
            "day": [
              9
            ]
          }
        }
      },
      "reservFlag": 0,
      "reserveChargeInfo2": {
        "reservChargeInfoDetail": {
          "reservChargeSet": false,
          "reservEndTime": "",
          "reservFatcSet": {
            "defrost": false,
            "airTemp": {
              "unit": 1,
              "value": "75"
            },
            "airCtrl": 0
          },
          "reservInfo": {
            "time": {
              "timeSection": 0,
              "time": "1200"
            },
            "day": [
              9
            ]
          }
        }
      },
      "offpeakPowerInfo": {
        "offPeakPowerFlag": 0,
        "offPeakPowerTime1": {
          "startTime": {
            "timeSection": 0,
            "time": "1200"
          },
          "endTime": {
            "timeSection": 0,
            "time": "1200"
          }
        }
      }
    }
  },
  "battery": {
    "batSoc": 82,
    "batState": 0,
    "sjbDeliveryMode": 0
  },
  "ign3": true,
  "ignitionStatus": "false",
  "lowFuelLight": false,
  "sideBackWindowHeat": 0,
  "engine": false,
  "sleepModeCheck": false,
  "defrost": false,
  "hoodOpen": false,
  "airConditionStatus": "false",
  "steerWheelHeat": 0,
  "tirePressureLamp": {
    "tirePressureWarningLampRearLeft": 0,
    "tirePressureWarningLampFrontLeft": 0,
    "tirePressureWarningLampFrontRight": 0,
    "tirePressureWarningLampAll": 0,
    "tirePressureWarningLampRearRight": 0
  },
  "trunkOpenStatus": "false"
}`
