### ISSUE TITLE
Feature request: add last update time to parsed vehicle status

### ISSUE THREAD

**Issue by PierreLevres** [Hacksore/bluelinky#110]
Output of vehicle status when parsed does not contain a timestamp of the lastupdate, request to add this.

**Comment by Hacksore** [comment]
@PierreLevres So currently on the location call we force the parse.


https://github.com/Hacksore/bluelinky/blob/develop/src/vehicles/european.vehicle.ts#L370
```ts
this._location = {
  latitude: data?.coord?.lat,
  longitude: data?.coord?.lon,
  altitude: data?.coord?.alt,
  speed: {
    unit: data?.speed?.unit,
    value: data?.speed?.value,
  },
  heading: data?.head,
};
```

Do you have an example response of the location call so I know what to add. Also, there is the option to allow for this to not parse automatically just like the status command.

That way if these properties every change from the API you can get the raw data.
