### ISSUE TITLE
Feature request: add refresh flag to vehicle.location function

### ISSUE THREAD

**Issue by PierreLevres** [Hacksore/bluelinky#111]
In EU the vehicle.location call forces a refresh of the car, while sometimes the cached location is enough to handle. This cached location can be read from vehiclestatus.location when vehiclestatus is called with (refresh=false). It might be more in line with vehiclestatus if vehicle.location can also be called with a refresh parameter (eq. defaulting to true) and for the non-refresh option vehiclestatus.location is returned.

**Comment by Hacksore** [comment]
@PierreLevres is this still needed?

**Comment by PierreLevres** [comment]
'Needed' is a big word, I'd call it 'wanted for consistency'.  Status: Refreshed or cached and then likewise Location: Refreshed or cached.

**Comment by gruijter** [comment]
Cached location is already available when doing fullStatus(refresh:false)

**Comment by PierreLevres** [comment]
I know. 
See my original question... see also why I made the request. Consistency.

**Comment by Hacksore** [comment]
Well unless you figure out how to make this consistent across regions I'm closing with wontfix for now.
