### ISSUE TITLE
ACC incorrectly mapping to 'AdaptiveCruiseControl'  in parsed vehicle status

### ISSUE THREAD

**Issue by PierreLevres** [Hacksore/bluelinky#113]
In the parsed vehicle status the 'acc'  is mapped as ' Adaptive Cruise Control' ..
see line 51 in common.interfaces.ts and line 283 in european.vehicle.ts
This should not be AdaptiveCruiseControl but 'Accessory'

Tested by bjakobs, see Discord channel

**Comment by Hacksore** [comment]
Can we please contribute to this sheet that helps with the mappings?

https://docs.google.com/spreadsheets/d/1FLVX2Y1XUi0F39Jvkkm_EeMuQbrVfAB0Lk5jc-No4Dc/edit?ouid=114789605208957738324&usp=sheets_home&ths=true

**Comment by PierreLevres** [comment]
created a PR for this (with changed code)
