### ISSUE TITLE
Login not possible for Hyundai in EU

### ISSUE THREAD

**Issue by tobiasamon** [Hacksore/bluelinky#115]
Hi there,

I get an error when trying to use bluelinky for my Ioniq BEV.

I checked out the code (latest version as of 160.03.2021) and try to "run debug". I created a config with my values and execute 'npm run debug'.

The POST to the signin URL return the following message:
 @EuropeController.login: [400] Bad Request on [POST] https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/signin - {"errId":"3c69d750-4486-4522-831e-5cf381606fe3","errCode":"4003","errMsg":"Invalid values","errBody":{"userId":"","remainCount":4,"remainTime":300}}

My config is as follows:
{
  "username": "MYMAIL@foo",
  "password": "MYPASSWORD",
  "pin": "MYPIN",
  "vin": "MYVIN"
}

Is there anything I can do?

**Comment by PierreLevres** [comment]
Wrong userid or password… 4 tries left within the next 300 seconds. Logout and login again from the app on your phone. If it tells you to migrate your account, do so, and be sure credentials between old BlueLink and new Hyundai account are the same, to avoid mix-ups.

**Comment by tobiasamon** [comment]
Hi,
thank you.
That helped. Both accounts need to have the same credentials.

**Comment by andig** [comment]
Same problem here. I can login to the app, but not using bluelinky. New Hyundai account with shared vehicle. Never had a bluelink account.
