### ISSUE TITLE
Feature request: Send POI / Destination to Nav

### ISSUE THREAD

**Issue by drygnet** [Hacksore/bluelinky#121]
Would love to be able to send a location to the nav in the car.

I could probably add the feature if someone could point me in the direction of some documentation,
I can't find anything, but would love to help.

**Comment by PierreLevres** [comment]
What region are you in? For Europe it is easy. Already implemented in my python lib. Will try to port that into develop. Don’t know for the other regions.

**Comment by PierreLevres** [comment]
https://github.com/PierreLevres/BlUVO/blob/master/bluvo_lib.py

**Comment by drygnet** [comment]
Nice! I'm in Europe (Sweden),

Im looking at the python lib now,
I think it's here:
https://github.com/PierreLevres/BlUVO/blob/227a2188ccdf3138318ff7935ef1486b17edc9ce/bluvo_lib.py#L860

and the poi_info object is set here:
https://github.com/PierreLevres/BlUVO/blob/01cf2990f148bbc36b16f0b01812db8129546735/generic_lib.py#L28

My usecase does not require the address-decoding via openstreetmap, I can construct the poi_info object in my code.

**Comment by drygnet** [comment]
My idea just for fun.

I wan't to use google maps on my phone, select och search for a place and use the apps share-function to send the location to the car.

The share function on iOS can be extended via the shortcuts app, but what google maps app sends to the shortcut is a short link with no actual info, so I need to build a service that can:
visit the link and get the redirect info from the response.
This response can contain a lat, lon -location or a google maps placeID, that can be decoded via the google maps API and then sent to my car... but the result will be a "Send to my car" -button in google maps, and that is cool :-)

**Comment by PierreLevres** [comment]
It takes an object like this as information to navigate to:

{'poiInfoList': [{'phone': '', 'waypointID': 0, 'lang': 1, 'src': 'HERE', 'coord': {'lat': -77.0365427, 'alt': 0, 'lon': 38.8950368, 'type': 0}, 'addr': 'Washington, District of Columbia, United States', 'zip': '', 'placeid': 'Washington, District of Columbia, United States', 'name': 'Washington, USA'}]}

**Comment by drygnet** [comment]
Very cool, actually works!

**Comment by Hacksore** [comment]
This was done for EU in #122, other regions still need a separate change.
