### ISSUE TITLE
feature request: list of trips per day

### ISSUE THREAD

**Issue by PierreLevres** [Hacksore/bluelinky#126]
in version 7.0.1 trip info is added in one way: listing and detailing all trips on  certain day.
However in the tripinfo-endpoint there is a second report possible: list the number of trips per day, though not detailing the trips of a day.
The difference from the other report is accomplished by changing tripPeriodType to 0 instead of 1. 

Output is when submitting this month as input:
{'monthTripDayCnt': 16,
 'tripAvgSpeed': 41,
 'tripDayList': [{'tripCntDay': 1, 'tripDayInMonth': '20210302'},
                 {'tripCntDay': 2, 'tripDayInMonth': '20210303'},
                 {'tripCntDay': 3, 'tripDayInMonth': '20210304'},
                 {'tripCntDay': 2, 'tripDayInMonth': '20210305'},

**Comment by neoPix** [comment]
So the input would be a month, and it will output the travel counts for each day of this month. Is this right ?

**Comment by PierreLevres** [comment]
In my python lib:
input 
{'setTripDay': any value or undefined or omitted,
 'setTripLatest': any value or undefined or omitted,
 'setTripMonth': '202103',
 'tripPeriodType': 0}

{'monthTripDayCnt': 16,
 'tripAvgSpeed': 41,
 'tripDayList': [{'tripCntDay': 1, 'tripDayInMonth': '20210302'},
                 {'tripCntDay': 2, 'tripDayInMonth': '20210303'},
                 {'tripCntDay': 3, 'tripDayInMonth': '20210304'},
                 {'tripCntDay': 2, 'tripDayInMonth': '20210305'},
                 {'tripCntDay': 3, 'tripDayInMonth': '20210306'},
                 {'tripCntDay': 4, 'tripDayInMonth': '20210307'},
                 {'tripCntDay': 3, 'tripDayInMonth': '20210310'},
                 {'tripCntDay': 3, 'tripDayInMonth': '20210313'},
                 {'tripCntDay': 2, 'tripDayInMonth': '20210314'},
                 {'tripCntDay': 2, 'tripDayInMonth': '20210316'},
                 {'tripCntDay': 4, 'tripDayInMonth': '20210317'},
                 {'tripCntDay': 6, 'tripDayInMonth': '20210320'},
                 {'tripCntDay': 4, 'tripDayInMonth': '20210321'},
                 {'tripCntDay': 2, 'tripDayInMonth': '20210324'},
                 {'tripCntDay': 5, 'tripDayInMonth': '20210326'},
                 {'tripCntDay': 6, 'tripDayInMonth': '20210328'}],
 'tripDist': 971,
 'tripDrvTime': 1182,
 'tripIdleTime': 298,
 'tripMaxSpeed': 134,
 'tripPeriodType': 0}

**Comment by PierreLevres** [comment]
This is my python code:
```
    def api_get_tripinfo(self, tripdate=datetime.today().strftime('%Y%m%d')):  # tripdate defaults to today, else yyyymmdd or yyyymm
        if len(tripdate) == 6: data = {'setTripMonth': tripdate, 'tripPeriodType': 0}
        else: data = {'setTripDay': tripdate, 'tripPeriodType': 1}
        url = BaseURL[self.userConfig.brand] + '/api/v1/spa/vehicles/' + self.vehicleConfig.id + '/tripinfo'
        headers = {
            'Authorization': self.controller.session.accessToken,
            'Content-Type': ContentJSON,
            'stamp': self.controller.session.stamp,
            'ccsp-device-id': self.controller.session.deviceId
        }
        response = requests.post(url, headers=headers, json=data, cookies=self.controller.session.cookies)
        if response.status_code == 200:

```

**Comment by neoPix** [comment]
Thanks, I'll give it a try and implement this soon.

**Comment by neoPix** [comment]
@PierreLevres the PR have been merged, should be available in the next release.
