### ISSUE TITLE
Newbie Help

### ISSUE THREAD

**Issue by fratinize** [Hacksore/bluelinky#132]
Please excuse my Ignorance first attempt at adding this to my environment.
 can Someone Please explain where this File

const BlueLinky = require('bluelinky');
and all below it is? 

IS this the Config? or is it something else? if it is something else I assume

{
  "username": "email",
  "password": "password",
  "pin": "pin",
  "brand": "kia" or "hyundai",
  "vin": "vin"
}
this with my Information is my Config.json?

Thank You for any Direction

**Comment by Hacksore** [comment]
You can pass the config into the constructor of the BlueLinky class like so. The debug scripts expect you to create a `config.json` file with the same data and import it.

```ts
const client = new BlueLinky({
  username: 'someguy@example.com',
  password: 'hunter1',
  brand: 'hyundai',
  region: 'US',
  pin: '1234'
});
```

**Comment by fratinize** [comment]
Please dumb this Down, I am Very New.
Not understanding the code below. It is more like the “Example” on git
 What is That file? Do I create it and Paste the example, in that file then edit with my data?

Do I Also Have config.json and How is that Formatted? Just the { }?

Thank You for your help


Frank

**Comment by Hacksore** [comment]
@fratinize If you're not a developer It's probably best to use something a little more friendly like node-red.

https://github.com/SondreNjaastad/node-red-contrib-bluelinky
