### ISSUE TITLE
get status- KIA - Canadian car issue

### ISSUE THREAD

**Issue by olivierjag2** [Hacksore/bluelinky#136]
i have bug since 5 days. When I try to get car status, I receive error 
"Cannot read property 'substring' of undefined"

Lock, Start, location, unlock, stop works fine with no error.

 - OS: node-red
 - Bluelinky Version 7.1
 - Region :CA

<img width="717" alt="image" src="https://user-images.githubusercontent.com/31319364/115142267-ccbf2f80-a00e-11eb-8898-d67c081a9719.png">

**Comment by neoPix** [comment]
Hi, the fix seems to be here.
Not integrated yet https://github.com/Hacksore/bluelinky/pull/137.

**Comment by olivierjag2** [comment]
do you know when ?

**Comment by Hacksore** [comment]
Should be fixed in the latest node-red addon.

**Comment by olivierjag2** [comment]
Thx!
