### ISSUE TITLE
Error handling in setNavigation wanted

### ISSUE THREAD

**Issue by PierreLevres** [Hacksore/bluelinky#138]
When sending more than 3 locations/waypoints in the call to setNavigation it errors. Also wayPointID > 2 errors. (So the maximum is 3 waypoints)

 - nodeJS
 - Bluelinky 7.1.0
 - EU

I propose to keep the first (final destination) and last two (meaning the first two waypoints on the route)

**Comment by Hacksore** [comment]
Should the lib really be responsible for handling every edge case/error scenario? This seems like it could just instead be handled in the downstream implementation, no? 

PR's are welcomed to fix this but I don't think there is much value here so I'm closing this. Feel free to continue the discussion nevertheless.

**Comment by PierreLevres** [comment]
Not really, they might remove the limitation in future versions. I’ve implemented the error handling in my NR implemementation (not in the node I PRred earlier).
