### ISSUE TITLE
Implementation discussion - Design Pattern & Region Inconsistencies 

### ISSUE THREAD

**Issue by Hacksore** [Hacksore/bluelinky#14]
So currently we are implementing the library with a "constructor" pattern which allows us to create the class instance and use it.

We also are letting the developer implement the login method explicitly but really that's not something you should have to manage.

```js
const config = require('./config.json');
const BlueLinky = require('bluelinky');

const client = new BlueLinky({
  username: config.username,
  password: config.password
});

(async () => {
  // do login explicitly
  const auth = await client.login();

  // we register and wait for a vehicle to get its features
  // this will query the api to gather the list for use on the next method(s)
  const vehicle = await client.registerVehicle(config.vin, config.pin);

  // call the status method
  const status = await vehicle.status();
  console.log(status);
})();
```

One solution I have to make this a bit more developer-friendly is to move to a factory pattern.
```js
const config = require('./config.json');
const BlueLinky = require('bluelinky');

// login was now moved into here implicitly
const client = BlueLinky.createClient({
  username: config.username,
  password: config.password
});

client.on('ready', async () => {
  // we register and wait for a vehicle to get its features
  // this will query the api to gather the list for use on the next method(s)
  const vehicle = await client.registerVehicle(config.vin, config.pin);

  // call the status method
  const status = await vehicle.status();
  console.log(status);
});
```

Now with that all being said, it seems that Canada and US API are rather similar by nature even though the endpoints are vastly different. However, from what @SondreNjaastad it looks like they don't use the VIN number for controlling their vehicles but a vehicle identifier.

This seems problematic as in US/Canada we do:
 ```js
  const vehicle = await client.registerVehicle(config.vin, config.pin);
```

But sounds like the EU will be doing:
```js
const vehicle = await client.registerVehicle(<vehicleIndentifier>, config.pin);
```

If something here stands out to you please feel free to discuss.

**Comment by altagir** [comment]
isn't the european vehicleIndentifier the same as vin ?
I don't see this as an issue
I believe the vin is not required also .
in a mobile app, I first download the list of vehicles known, they have the VIN listed there
then the user select a list of its available vehicule, pick up one, and you have your current selected VIN 
so I see the VIN as just the currenly selected vehicle.

**Comment by altagir** [comment]
rectification, after code reading
in my code, 
- I login , get an accessToken
- get list of all vehicles (once, cache it, store it)
   this list has a vehicleId and VIN information for each car
- any API call needed later to access the car is vehicleID in headers, never VIN.  
    the VIN is only used once to get the vehicleId associated with your VIN, but is it absolutely useless (but required for the setup of official mobile app)

    in Canada and US , the VIN is clearly visible on the dashboard when you look from the outside.

**Comment by Hacksore** [comment]
So far this is the new implementation I have come up with. Not really thinking it's needed to have a factory pattern, we can still achieve a better flow by calling login internally and having a client-ready event.

```js
const config = require('./config.json');
const BlueLinky = require('./dist/index');

const { username, password, vin, pin } = config;
const client = new BlueLinky({
  username,
  password,
  region: 'US'
});

client.on('ready', async () => {
  const vehicle = await client.registerVehicle({ vin, pin });
  const status = await vehicle.status();  
  console.log(status);
});

```

**Comment by Hacksore** [comment]
`develop` now has a good base.
