### ISSUE TITLE
[EU] Kia login fails

### ISSUE THREAD

**Issue by andig** [Hacksore/bluelinky#143]
**Describe the bug**

**Usefull info(please complete the following information):**
 - OS: macOS
 - Bluelinky Version: bluelinky@7.2.0
 - Region: EU

**Additional context**

This is what I see when I run the login via proxy:

```
❯ GLOBAL_AGENT_HTTP_PROXY=http://localhost:9090 node -r 'global-agent/bootstrap' index.js
[2021-04-27 12:39:08] error: @EuropeController.login: sign in with EuropeanBrandAuthStrategy failed with error Error: @EuropeanBrandAuthStrategy.login: Authentication failed with message : Invalid username or password.
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Url.parse (url.js:160:3)
    at Object.urlParse [as parse] (url.js:155:13)
    at O.<anonymous> (/Users/andig/htdocs/bl/node_modules/bluelinky/dist/index.js:17:164013)
    at Generator.next (<anonymous>)
    at p (/Users/andig/htdocs/bl/node_modules/bluelinky/dist/index.js:17:85)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

The last request executed is against `https://prd.eu-ccapi.kia.com:8080/api/v1/user/signin`

**Comment by neoPix** [comment]
Hi @andig,

This case might occur when the kia (also the case with hyundai) auth system requires you to change your password.

If you have the skill or the time to do so, it would be nice to have the http(s) redirect sequence from `https://eu-account.kia.com/auth/realms/eukiaidm/protocol/openid-connect/auth` to the error to integrate the password change management part.

On the password change page, they're a `skip` button and it would be nice to have both the url of this page (to identify it by code) and form or link url of the skip button to automate the skip action.

**Comment by andig** [comment]
thanks @neoPix, much appreciated

> If you have the skill or the time to do so, it would be nice to have the http(s) redirect sequence from https://eu-account.kia.com/auth/realms/eukiaidm/protocol/openid-connect/auth to the error to integrate the password change management part.

As for the bluelinky flow there is not much going on:

```
GET /auth/realms/eukiaidm/protocol/openid-connect/auth?client_id=..&scope=openid%20profile%20email%20phone&response_type=code&hkid_session_reset=true&redirect_uri=https://prd.eu-ccapi.kia.com:8080/api/v1/user/integration/redirect/login&ui_locales=en&state=... 
HTTP/1.1 200 OK

POST /auth/realms/eukiaidm/login-actions/authenticate?session_code=...&execution=...&client_id=...&tab_id=07NPy-uwMlI
HTTP/1.1 200 OK
```

After that it continues:

```
https://prd.eu-ccapi.kia.com:8080/api/v1/user/oauth2/authorize?response_type=code&state=test&client_id=...&redirect_uri=https://prd.eu-ccapi.kia.com:8080/api/v1/user/oauth2/redirect
HTTP 302

https://prd.eu-ccapi.kia.com:8080/web/v1/user/authorize?cache=reset
HTTP 200
```

**Comment by andig** [comment]
Use logged out of the app and back in, then had to change his password. Unfortunately that was beyond my control for tracing. Thanks for your support!
