### ISSUE TITLE
Engine not starting (via homebridge bluelink plugin which uses BlueLinky)

### ISSUE THREAD

**Issue by yonigold1** [Hacksore/bluelinky#145]
**Describe the bug**
The engine of my Hyundai does not successfully start.

**Usefull info(please complete the following information):**
 - OS: Homebridge (Linux)
 - Bluelinky Version v5.2.3
 - Region: CA 

**Additional context**
When trying to start the engine through Apple HomeKit the command gets sent however the command doesn't seem to get executed. To elaborate, the command to start the ignition IS in fact going through however it seems like the command that's being sent is incorrect as the BlueLink app DOES in fact register that there is a command being sent however the command seems to have no action. When I try to toggle the Ignition from HomeKit if i go right to the BlueLink app and trying to execute any remote action it says "We are currently processing an earlier inquiry for your vehicle please wait 90 seconds..." So it received the ignition start command its just failing to execute. 

The developer of the Homebridge plugin thinks its an issue with BlueLinky. Please let me know if theres anything i can try to help further debug this issue.

**Comment by Hacksore** [comment]
@yonigold1 can you share the start config you use? 

In the past others have had success in `CA` with this https://github.com/SondreNjaastad/node-red-contrib-bluelinky/issues/18#issuecomment-754851538

**Comment by yonigold1** [comment]
when u say the start of the config what do u mean? like my config for homebridge?

**Comment by altagir** [comment]
@Hacksore 
I tested by curiosity latest main, and yes it got broken

value": "6H" is wrong, it should be "06H" (17 degrees)
when i use 22 degrees ("value": "10H"), issue does not show.

I remember to see some refacto pass by to have common function
may be refer to my initial implementation

regards

```
 info: {
  "hvacInfo": {
    "airCtrl": 1,
    "defrost": true,
    "heating1": 1,
    "airTemp": {
      "value": "6H",
      "unit": 0,
      "hvacTempType": 1
    }
  }
```

**Comment by yonigold1** [comment]
So to fix this issue one has to change those values?

**Comment by athal7** [comment]
Here is the relevant code in the homebridge plugin:
https://github.com/athal7/homebridge-hyundai-bluelink/blob/main/src/services/ignition.ts

And the type for the config that is referenced:
https://github.com/athal7/homebridge-hyundai-bluelink/blob/main/src/config.d.ts

**Comment by Hacksore** [comment]
I'm sure this must be related to #96 based on the feedback here.

**Comment by yonigold1** [comment]
So what would this mean? how would i got about fixing this for myself?

**Comment by altagir** [comment]
I think it is our side to fix, and just add a padding 0 to the hex value

**Comment by altagir** [comment]
I had this initially for canadian
 ```
const airTemp = startConfig.airTempvalue
      if (airTemp != null) {
        if (airTemp > 27 || airTemp < 17) {
          return Promise.reject("air temperature should be between 17 and 27 degrees");
        }
        let airTempValue: string = (6 + (airTemp - 17) * 2).toString(16).toUpperCase() + 'H';
        if (airTempValue.length == 2) {
          airTempValue = '0' + airTempValue
        }
        body.hvacInfo['airTemp'] = { value: airTempValue, unit: 0, hvacTempType: 1 }
      } else if ((startConfig.airCtrl ?? false) || (startConfig.defrost ?? false)) {
        return Promise.reject("air temperature should be specified")
      }
```
Notice the 
```
if (airTempValue.length == 2) {
         airTempValue = '0' + airTempValue
}
```
@Hacksore , could you follow up with the fix, I am really overloaded at work

**Comment by yonigold1** [comment]
Okay if you guys want me to test just let me know :)

**Comment by Hacksore** [comment]
So this is really just because our [celciusToTempCode](https://github.com/Hacksore/bluelinky/blob/181104c0c5c0b78e7cf0e7309db0b42050217e05/src/util.ts#L14) method doesn't work right. 

Let's close this issue as duplicate as the fix should be with #96 but we need someone willing and able to understand wtf Hyundai/Kia is doing.

**Comment by altagir** [comment]
@Hacksore it was just missing the padding 0 ....
I am not sure it is related, should also impact US et EU

**Comment by yonigold1** [comment]
Will someone let me know when this is fixed so i can give this a try with my car :)

**Comment by yonigold1** [comment]
any update yet?

**Comment by james5294** [comment]
US model - 2021 palisade doing the same.. any fix?

**Comment by Hacksore** [comment]
@james5294 can you raise a new issue with all the details?

**Comment by james5294** [comment]
> @james5294 can you raise a new issue with all the details?

opened

**Comment by james5294** [comment]
@Hacksore opened!

**Comment by yonigold1** [comment]
I'm still having an issue with this. Is there anyone that's got theirs to work?

**Comment by james5294** [comment]
> I'm still having an issue with this. Is there anyone that's got theirs to work?

https://github.com/Hacksore/bluelinky/issues/180
