### ISSUE TITLE
[EU] Unable to start ICE (internal combustion engine) car (Hyundai Tucson 2021)

### ISSUE THREAD

**Issue by NiccoStar86** [Hacksore/bluelinky#147]
Hi everybody, I try to implement via Node-RED and Home Assistant, some features to send/retrive data form my new Hyundai Tucson 2021 :)

While other functions like "car-status", "car-odometer", "car-lock" and "car-unlock" works correctly, when I try to use the "car-start" following the documentation ...

<img width="555" alt="Schermata 2021-06-13 alle 12 31 37" src="https://user-images.githubusercontent.com/7814756/121803939-10679b80-cc44-11eb-88c7-39c887e05ce0.png">

... I sent this via "inject" in "msg.payload":

<img width="370" alt="Schermata 2021-06-13 alle 12 31 23" src="https://user-images.githubusercontent.com/7814756/121803945-1e1d2100-cc44-11eb-80c3-191af9488035.png">

... I get this response:

<img width="529" alt="Schermata 2021-06-13 alle 12 32 25" src="https://user-images.githubusercontent.com/7814756/121803947-207f7b00-cc44-11eb-9cd9-d3eb8018c220.png">

I'm a neophyte of Node-RED and maybe I am doing something wrong ... From the answer I interpreted that maybe ICE machines in Europe are not remotely bootable? Only EVs?

Thanks for any inputs you can provide me :)

**Comment by Hacksore** [comment]
@NiccoStar86 Those question marks should not be in the keys, that's most likely the issue.

**Comment by NiccoStar86** [comment]
> @NiccoStar86 Those question marks should not be in the keys, that's most likely the issue.

Thank you @Hacksore ! Also without the question marks, I received the same response ... 

<img width="320" alt="Schermata 2021-06-13 alle 14 40 00" src="https://user-images.githubusercontent.com/7814756/121807688-858f9c80-cc55-11eb-9de4-8e6aeb17a95a.png">

<img width="433" alt="Schermata 2021-06-13 alle 14 40 46" src="https://user-images.githubusercontent.com/7814756/121807698-888a8d00-cc55-11eb-8b05-ec9e63344eed.png">

From the response "Undefined Error - Vehicle is not EV" it would seem that this is not possible for ICE cars, although "Undefined Error" is very strange!

**Comment by Hacksore** [comment]
@neoPix I think this no longer works for ice vehicles :)

https://github.com/Hacksore/bluelinky/blob/181104c0c5c0b78e7cf0e7309db0b42050217e05/src/vehicles/european.vehicle.ts#L38

**Comment by neoPix** [comment]
I did some testing on this with on off the Jeedom plugin users and by November 2020 it was not possible.

Is it possible in the app ?

If not, this might be why it also does not work in Bluelinky.

**Comment by NiccoStar86** [comment]
Thanks @neoPix, actually from the application it is not possible to start the machine ... I was hoping to be able to do this through Bluelinky :) also because my Tucson was delivered with the remote control that allows remote ignition, so I don't see why not allow the same operation to be done remotely via app/api. I close this (not) bug! Thanks to everyone.
