### ISSUE TITLE
Vehicle status not up-to-date

### ISSUE THREAD

**Issue by djungbluth** [Hacksore/bluelinky#152]
**Describe the bug**
evStatus.batteryStatus received by vehicle.status() is not up-to-date and in sync with what the official Bluelink App displays. For instance, evStatus.batteryStatus is "37" although the Bluelink App shows "80" which is correct.

Before this observation, I noticed that Bluelinky's response was only updating when refreshing the status in the Bluelink App.

**Usefull info(please complete the following information):**
 - OS: Linux
 - Bluelinky Version 7.3.0
 - Region: EU
 - Brand: Hyundai

**Additional context**
The use case is to poll the Bluelink API (every ~15 minutes or so depending on whether driving or charging) and to print the SoC on a bluetooth-connected display. Sequence in pseudo-code is:

```
start:
client = new BlueLinky({config});

when ready, vehicle = client.getVehicle(vin);
response = await vehicle.status();
print response.evStatus.batteryStatus;

wait 15 minutes
goto start
```

**Comment by neoPix** [comment]
Is it possible that a few days ago the battery level was at 37%. I'm also having this issue with the status from server values, It look's like Hyundai/Kia are having a cache in place and that it's flawed.

Anybody else with this issue and/or hints on its root cause ?

**Comment by djungbluth** [comment]
Correct, 37% was the old status some time ago.

It became apparent that 37% was still displayed in another official Bluelink app that is installed on a second phone. Once refreshed there, the up-to-date status was also finally reported by using Bluelinky.

Agreed, there seems to be some crazy cache in place which is not refreshed when Bluelinky logins and queries the vehicle‘s status.

**Comment by Hacksore** [comment]
In theory, when you use `refresh: true` should it always be fetching the latest data from the vehicle though?

**Comment by djungbluth** [comment]
I guess this means one should use „vehicle.status({„refresh“:true})“?

Interestingly, w/o refresh the API runs also into a rate limit. What is the purpose of refresh=false by default?

**Comment by Hacksore** [comment]
> I guess this means one should use „vehicle.status({„refresh“:true})“?
> 
> Interestingly, w/o refresh the API runs also into a rate limit. What is the purpose of refresh=false by default?

Querying your car is expensive with `refresh` as it has to connect to the 3g/4g modem. If you did that enough you'll definitely kill the battery 😅

**Comment by djungbluth** [comment]
- How many times before battery is getting drained?
- Does this apply to electric vehicles, too?
- Is 12V battery status returned by vehicle.status() and how to know before battery is „killed“?

BTW, awesome project and keep up your great work! Really cool!

**Comment by PierreLevres** [comment]
Depends on multiple factors. I would think about  100 times.
Yes also applies on EVs. Even more since that 12v battery is rather small
The battery status is only updated when driving or when shutting down the engine. So no indication it is about to die.

**Comment by mpucherSmIT** [comment]
I had the query running every 20 minutes (24h) and it killed the battery twice. So depending on the battery condition something around 70 requests a day is enough to drain it completely.

I'm now at every 3 hours from 8 am to 8 pm and that seems to be fine (so far)

**Comment by djungbluth** [comment]
> I had the query running every 20 minutes (24h) and it killed the battery twice. So depending on the battery condition something around 70 requests a day is enough to drain it completely.
> 
> I'm now at every 3 hours from 8 am to 8 pm and that seems to be fine (so far)

Depending on whether engine is on and/or battery is charging, I reduce the intervals for polling..

There isn‘t a webhook for vehicle status updates, right?
