### ISSUE TITLE
[CA] Support Kia EV charging methods

### ISSUE THREAD

**Issue by sacua** [Hacksore/bluelinky#157]
I'm not sure if this is the best place to write, but I will give it a try. So I'm using node-red-contrib-bluelinky which I understand also use this code. So, I have a Kia EV car in Canada and I would like to be able to set charge target and start and stop the charge, which seems to not have been implemented for Kia in Canada with bluelinky (I'm maybe wrong). 

I've try to make some modification in the source code which was a total failure (had to reinstall Node-red since was no longer functionning properly...). 

So, what I've done, with Fiddler I've capture the internet traffic for some requests that seems to not be implemented.

So, for starting the charge (the PIN is send in the request obviously):
the url request (if the right terminology) : tods/api/evc/rcstrt

for stoping the charge with the PIN send:
the url request:  tods/api/evc/rcstp

for setting the charge target:
the url request: tods/api/evc/setsoc
with the following sent JSON object (plugType = 0 is fast and 1 is slow)
![InkedCapture_LI](https://user-images.githubusercontent.com/59889660/129119177-b64b52e8-0a31-41d0-a57d-5393ca4e14c0.jpg)

Hope this can help to implement those capabilities for Kia EV car in Canada and those feature will be reflected in the node-red-contrib-bluelinky.

Really appreciate all the works that have been done yet.
Best,

**Comment by Hacksore** [comment]
Created https://github.com/Hacksore/bluelinky/tree/feat/ca-ev-charge which would need someone to test it out 😅.

**Comment by sacua** [comment]
To bu sure, in my .node-red directory, I should run the command npm install https://github.com/Hacksore/bluelinky/tree/feat/ca-ev-charge. Then, I will be able to test it with node-red?

**Comment by Hacksore** [comment]
@sacua not quite - ideally this is how you should test before we think about getting this added to the node-red plugin.

1. Open a directory you wish to clone the `bluelinky` project to in your terminal
2. Run `git clone -b feat/ca-ev-charge https://github.com/Hacksore/bluelinky.git`
3. Run `cd bluelinky`
4. Create a `config.json` with this structure in the project dir and enter your specifics
```json
{
  "username": "tbd", 
  "password": "tbd",
  "pin": "tbd"
}
```
5. Run "npm run debug"
6. Follow the prompts to select CA -> Kia -> [EV] set charge targets

This should help us and figure out if the implementation was the right first shot. Please share any relevant logs that are redacted here.

**Comment by sacua** [comment]
Sorry for my limited knowledge in that area, but I certainly do something
that is not right, I have the following error in the terminal:

[image: image.png]

At first, I've run it in my home directory and then due to the error, I've
try to run it in the node_modules directory.

I may not answer for the next few hours.

thanks a lot for your help!
--
Samuel



Le jeu. 12 août 2021, à 15 h 17, Sean Boult ***@***.***> a
écrit :

**Comment by Hacksore** [comment]
@sacua I forgot to include a step please check the instructions again.

**Comment by sacua** [comment]
The start and stop the charging is working! However, the charging target does not seems to work, although no error are appearing in the terminal. When I look into UVO or go into my car, the set charging target does not change in comparison to the previous one.

```
[2021-08-12 17:04:41] debug: Begin setChargeTarget
[2021-08-12 17:04:41] info: Begin pre-authentication
[2021-08-12 17:04:41] debug: [https://myuvo.ca/tods/api/vrfypin] {} {}
[2021-08-12 17:04:41] debug: shouldRefreshToken: false
[2021-08-12 17:04:41] debug: Token not expired, no need to refresh
[2021-08-12 17:04:43] debug: [https://myuvo.ca/tods/api/evc/setsoc] {} {"pin":"xxxx","pAuth":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","tsoc":[{"plugType":0,"targetSOClevel":70},{"plugType":1,"targetSOClevel":100}]}
[2021-08-12 17:04:43] debug: shouldRefreshToken: false
[2021-08-12 17:04:43] debug: Token not expired, no need to refresh
targets : OK
```
What I've realised is the label "targetSOClevel" may need to be only "level".

**Comment by Hacksore** [comment]
@sacua can you run a `git pull` and again as I've made the change you pointed out for charge targets.

**Comment by sacua** [comment]
@Hacksore, it is working! Thanks a lot

**Comment by sacua** [comment]
Hi,
I don't want to want

**Comment by Hacksore** [comment]
@sacua was leaving open so I remember to publish the latest version 😬

**Comment by sacua** [comment]
Oups sorry, I didn't want to do that, I want to remove a message that I
publish accidentally.

Le jeu. 19 août 2021, à 17 h 00, Sean Boult ***@***.***> a
écrit :

**Comment by sacua** [comment]
Hi Sean,
I don't want to put any pressure since I know you do this for fun. When do
you think the new feature you have implemented for Canadian electric car
will be available in node-red-contrib-bluelinky?
Thanks,
--
Samuel Cuerrier Auclair
Cell: 418-805-5131

**Comment by Hacksore** [comment]
@sacua Would you mind opening an issue for this in the node-red addon repo?

**Comment by sacua** [comment]
Since the last update made today, everything is working now. Thanks!
