### ISSUE TITLE
newb

### ISSUE THREAD

**Issue by darthjinxxx** [Hacksore/bluelinky#160]
wow how do i even start all this? i used someones shortcut several weeks back and it utitlized this api.  However they no longer own a hyundai so I am trying to correct the shortcuts.  who can help me

**Comment by Hacksore** [comment]
You could see if anyone on the shortcuts subreddit is willing to revive it - not much bandwidth from me.

https://www.reddit.com/r/shortcuts/
https://editor.scpl.dev/
