### ISSUE TITLE
batsoc sometime undefined

### ISSUE THREAD

**Issue by CrAsH0v3r** [Hacksore/bluelinky#174]
Hi, It's more a question than a issue, 
I noticed last summer and then yesterday that sometime my Kona 2021 do not return the value for the batsoc field. 

My script based on Bluelinky was crashing so after a bit of investigation, I saw that the JSON file was sometime missing 1 (or maybe more?) fields. It is the case for batsoc this morning. 

 - OS: Any
 - Bluelinky : Any 
 - Region: CA

The API call is this one : https://mybluelink.ca/tods/api/rltmvhclsts.

It is not a bluelinky bug as it on the server/car side. I confirmed that by calling the API by myself. 

The last read value was 68. Maybe under a specific point, lets say 50, it returns nothing? Any idea?

Thanks!

**Comment by Hacksore** [comment]
I've opened discussions for this project that we can use for requests like this. That or discord would be a good place to continue this discussion in more detail.

https://github.com/Hacksore/bluelinky/discussions
https://discord.gg/fpHkWVp26H
