### ISSUE TITLE
Kia Canada

### ISSUE THREAD

**Issue by olivierjag2** [Hacksore/bluelinky#175]
** the bug**

**Usefull info(please complete the following information):**
 - OS: [e.g. macOS, Windows, Linux]
 - Bluelinky Version 7
 - Region: ça

**Additional context**

Kia change the app and node red don't work since

**Comment by sacua** [comment]
Yes I support his saying. 

The biggest change, I believe is the following: the host is no longer myuvo.ca but kiaconnect.ca

All the API does not seems to have change except the login which is now: /tods/api/v2/login instead of /tods/api/lgn

**Comment by olivierjag2** [comment]
Do you Fix the problem?

**Comment by sacua** [comment]
Hi,
By making some test with npm debug and making some modification to the src/constant/canada.ts.

The only modification that need to be done I believe is the host name which is now "kiaconnect.ca"

All the other commands seems to work except the "Start". I have an EV vehicule, so maybe with npm debug the "Start" does not work for EV vehicule (just a guest).

Also, thans to have develop this fantastic tools!

**Comment by Hacksore** [comment]
@sacua Mind sending a PR for this?

**Comment by sacua** [comment]
Can try, but it will be the first time.


Le ven. 5 nov. 2021, à 09 h 24, Sean Boult ***@***.***> a
écrit :

**Comment by sacua** [comment]
Everything seems solve here for Canada! Just need to update the node red contrib bluelinky.

**Comment by olivierjag2** [comment]
how update  red node repo?

**Comment by Hacksore** [comment]
@olivierjag2 you'd want to reinstall the node-red addon and it should get the latest bluelinky.

This was fixed in #176
