### ISSUE TITLE
New account access rights (telefon, e-mail and such) not working with EU hyundai brand

### ISSUE THREAD

**Issue by mpucherSmIT** [Hacksore/bluelinky#179]
**Describe the bug**
I updated to v7.6.2 this morning and it stopped working. The console output said:

[2021-11-07 10:12:17] error: @EuropeController.login: sign in with EuropeanBrandAuthStrategy failed with error Error: @EuropeanBrandAuthStrategy.login: Cannot find the argument userId in https://eu-account.hyundai.com/auth/realms/euhyundaiidm/login-actions/authenticate?client_id=64621b96-0f0d-11ec-82a8-0242ac130003&tab_id=9MNAFFChH1w.

As you can see, the new clientId is already there. By accident I opened the URL https://eu-account.hyundai.com/auth/realms/euhyundaiidm/login-actions/authenticate?client_id=64621b96-0f0d-11ec-82a8-0242ac130003&tab_id=9MNAFFChH1w in a browser window to see what happens and it navigated me to a hyundai account login screen. I entered my login credentials and after login I was asked to allow access to account data. After I accepted bluelinky worked again...

**Usefull info(please complete the following information):**
 - OS: linux ubuntu server
 - Bluelinky Version 7.6.2
 - Region: EU
 - Brand: hyundai

**Comment by gruijter** [comment]
@mpucherSmIT if you downgrade bluelinky to 7.6.1 your login is working again or not? Just want to make sure something broke in the 7.6.2 release.

**Comment by Hacksore** [comment]
Assuming this has to do with the account migrations debacle.

I will close this issue for now but please don't hesitate to add more info here that might be relevant.
