### ISSUE TITLE
Vehicle Not Found Error

### ISSUE THREAD

**Issue by rikardkjell** [Hacksore/bluelinky#182]
When running the example js-code on a Raspberry Pi I get this error message...

(node:3742) UnhandledPromiseRejectionWarning: Error: Vehicle not found: ###VIN-NO###!
    at se.getVehicle (/home/pi/node_modules/bluelinky/dist/index.js:17:51727)
    at se.client.on (/home/pi/node_modules/bluelinky/run.js:13:26)
    at se.emit (events.js:182:13)
    at se.<anonymous> (/home/pi/node_modules/bluelinky/dist/index.js:17:51367)
    at Generator.next (<anonymous>)
    at s (/home/pi/node_modules/bluelinky/dist/index.js:17:85)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:3742) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3742) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

 - OS: Linux running on a Raspberry Pi (Model B+)
 - Bluelinky Version v7.6.2
 - Region: EU
 - Brand: Kia

**Comment by PierreLevres** [comment]
Vehicle not found: ###VIN-NO###!

Seems like you did not enter your vin number in your Config file?



> Op 24 nov. 2021 om 20:22 heeft rikardkjell ***@***.***> het volgende geschreven:
> 
> Vehicle not found: ###VIN-NO###!

**Comment by rikardkjell** [comment]
Sure did. Just didn't wanna publish my VIN-number here on GitHub so that part I didn't pass on ;-)

**Comment by Hacksore** [comment]
I do think this could have been related to casing - I've changed it to lower both sides and this should be the solution here.

Will be included in the next release.
