### ISSUE TITLE
[EU] 503 on vehicle status

### ISSUE THREAD

**Issue by mintgroen** [Hacksore/bluelinky#188]
I use Node red to call the API once a week to get the mileage. I noticed that the mileage was not updated so I retried it manually today, but no juice.

Some snippets from the node response:

{"source":{"name":"**HTTPError**","hostname":"prd.eu-ccapi.hyundai.com","method":"GET","path":"/api/v2/spa/vehicles/

"baseUrl":"https://prd.eu-ccapi.hyundai.com:8080/","method":"GET"},"**statusCode":503,"statusMessage":"Service Unavailable",**"headers"

"x-ratelimit-limit":"100","x-ratelimit-remaining":"95","x-ratelimit-reset":"1640638736","content-length":"149","connection":"close"},"body":{"retCode":"F","resCode":"5031","resMsg":"**Unavailable remote control - Service Temporary Unavailable"**,"msgId":"2342134234423423"}},"name":"ManagedBluelinkyError"}

The official app works as expected.

I've saved and restarted the flow, but still no valuable answer from the API. Is the server actually down? (log4j? :?), or it is a client side issue?

**Comment by PierreLevres** [comment]
What node in node red did you use? Car-fullstatus ? If so try the car-odometer node. 
Did this start when you updated the navigation software on your car ?

My hunch is that car-location and car-fullstatus are failing on newest car software when car is in deep sleep and/or without proper GPS coverage (in a garage)

**Comment by PierreLevres** [comment]
> The official app works as expected.
Also for a location refresh?

> I've saved and restarted the flow, but still no valuable answer from the API. Is the server actually down? (log4j? :?), or it is a client side issue?

If you get a response in the app the server isn't down :)

**Comment by mintgroen** [comment]
> What node in node red did you use? Car-fullstatus ? If so try the car-odometer node. Did this start when you updated the navigation software on your car ? My hunch is that car-location and car-fullstatus are failing on newest car software when car is in deep sleep and/or without proper GPS coverage (in a garage)

I've updated the navigation last week yes. But my car is on the driveway with a clear view of the sky and 5G reception.

I use car-fullstatus for some other details, but just tested with the Get car odometer, without any results.

>If you get a response in the app the server isn't down :)

Yes you are correct, the server is alive. Although the service does not respond as expected. Is Bluelinky ringing at the wrong door?

**Comment by Hacksore** [comment]
Maybe the call has changed in some way where our implementation is no longer working effectively?

I have to leave this one to the EU maintainers if they have time

cc @neoPix @SondreNjaastad

**Comment by PierreLevres** [comment]
I updated my car software yesterday tot the latest version, but still /location fails after a few hours when the car goes to sleep.
I implemented a workaround in node-red: if refreshed full status fails (because fail on /location call) then get the cached full status and overwrite the vehicleStatus key with a refreshed (non-full) status.
Looks a lot like the way the public async fullStatus(input: VehicleStatusOptions) is already written, we could omit throwing an  Err if /location fails.

**Comment by neoPix** [comment]
Checked the Android app code :
- The HTTP request is still the same,
- The location once received is stored locally on the phone,
- When the request fails, a message is shown and the stored position is used as a substitute,
So :shrug:, appears that the location requests can sometimes fail

**Comment by Hacksore** [comment]
@neoPix if it randomly fails then it's more just a service side issue and not something we can really fix.

I'm going to close this and just mention that as a consumer you need to handle errors in your code.
