### ISSUE TITLE
code need update

### ISSUE THREAD

**Issue by ad666666** [Hacksore/bluelinky#190]
await got(`${this.environment.baseUrl}/api/v1/spa/notifications/register`, 

    body: {
          pushRegId: credentials.gcm.token,
          pushType: 'GCM',
          uuid: this.session.deviceId,
        },

****************************
bluelink new version  
on body  add      providerDeviceId
so  new body:{
 pushRegId: credentials.gcm.token,
          pushType: 'GCM',
          uuid: this.session.deviceId,
providerDeviceId:‘’
}
providerDeviceId=BluelinkApp.mPushService.getDeviceId()

**Comment by neoPix** [comment]
Hi @ad666666, do you get any kind of error when `providerDeviceId` is not set ?

**Comment by ad666666** [comment]
will not ,i read bulelink code just now,providerDeviceId  be  use for set message to user
i am a chinese developer ,my english is not good,

**Comment by Hacksore** [comment]
If `providerDeviceId` is needed now we need a good idea of how to do that.

@ad666666 Please provide what the value should be and if it's dynamic or static.

**Comment by Hacksore** [comment]
Consider opening a new issue if more information is discovered on this.
