### ISSUE TITLE
EU EV driveHistory errs with parameter All (2)

### ISSUE THREAD

**Issue by PierreLevres** [Hacksore/bluelinky#192]
When driveHistory is called with parameter historyDrivingPeriod.ALL (in casu 2), the function fails on mapping the output.
My raw output of the API call (response.body.resMsg) is 
{
  drivingInfoDetail: [
    {
      drivingPeriod: 0,
      drivingDate: '20220112',
      totalPwrCsp: 9026,
      motorPwrCsp: 5983,
      climatePwrCsp: 1463,
      eDPwrCsp: 1580,
      batteryMgPwrCsp: 0,
      regenPwr: 4543,
      calculativeOdo: 60
    }
  ]
}

The wrapper function fails on "response.body.resMsg.drivingInfo.map"
 
 - Bluelinky Version 7.6.2
 - Region: EU

**Comment by neoPix** [comment]
Hi @PierreLevres,

I'll give a look to this. Maybe the API changed since our last implementation.
