### ISSUE TITLE
EU EV driveHistory gives ' Invalid date' with parameter Month (1)

### ISSUE THREAD

**Issue by PierreLevres** [Hacksore/bluelinky#193]
When driveHistory is called with parameter historyDrivingPeriod.MONTH (in casu 1), dates in the output are parsed to ' InvalidDate' by the function parseDate in srs/util.ts. That function does not know how to cope with  drivingDate: '202201'.
Suggested solution to add day 01 ? 

The raw output of the API call (response.body.resMsg) is 
drivingInfoDetail: [
    {
      drivingPeriod: 1,
      drivingDate: '202201',

And is is reformatted to:
  history: [
    {
      period: 1,
      rawDate: '202201',
      date: **Invalid Date**,
 

 
 - Bluelinky Version 7.6.2
 - Region: EU

**Comment by neoPix** [comment]
Hi @PierreLevres,

Nice catch, I'm adding this to my todo :wink:

- [ ] Manage the date conversion when the day information is absent (eg: `202201`)
- [ ] Add unit tests for this specific case
