### ISSUE TITLE
Confusing name of parameter windscreenheating

### ISSUE THREAD

**Issue by PierreLevres** [Hacksore/bluelinky#197]
In calling start vehicle in EU, EV two boolean parameters are passed.

defrost  --> defrosting the front windscreen;  maps to 'defrost' in API
windscreenheating --> heats the rear window, side mirrors and steering wheel ;  maps to ' heating1 ' in API

The name second one is pretty confusing, since it doesn't do anything with the windscreenheating. I'd like it to be renamed BUT:
Since a lot of implementations use those parameters (eg. the node-red-contrib-bluelinky) it is hard to change, would be a breaking change. If not changeable, my suggestion is to document this well.
For node-red-contrib-bluelinky I submitted a PR [https://github.com/SondreNjaastad/node-red-contrib-bluelinky/pull/63/commits/6fc201ec9dbdb00d139fb7663330c23ded514b2e](url)

**Comment by Hacksore** [comment]
@PierreLevres The plan is to rename all of them for consistency. 

It's documented here https://bluelinky.readme.io/reference/start

**Comment by PierreLevres** [comment]
> @PierreLevres The plan is to rename all of them for consistency.
> 
> It's documented here https://bluelinky.readme.io/reference/start

How can I contribute and give feedback? 
In the current implementation, in the /start command in Europe:
unit : string "C" for Celsius (not integer)
defrost : defrosts frontwindow and does not warm backwindow and sidemirrors and steeringwheel
heating1 : does warm backwindow and sidemirrors and steeringwheel

**Comment by Hacksore** [comment]
I'd say here is a good place to discuss them and make updates.

Please propose any other changes to the docs then as we implment the change for `8.x` we can follow this.

Name | Type | Comment
-- | -- | --
hvac | string | Turn on the HVAC
duration | string | How long to run the vehicle's engine (max 10)
temperature | integer | Temp in Fahrenheit for the HVAC
defrost | boolean | Turn on defrosters and side mirrors
heatedFeatures | boolean | Heated features like the steering wheel and rear window
unit | string | Use celcius or farenhight for HVAC temp

**Comment by PierreLevres** [comment]
In the new version renaming has been done. I will close this question.
