### ISSUE TITLE
Remote Start fails

### ISSUE THREAD

**Issue by SteffeyDev** [Hacksore/bluelinky#198]
**Describe the bug**
I'm trying to use bluelinky to control my 2022 Hyundai Tucson Hybrid, and everything is working great except the remote start feature.  I get the error `Failed to start vehicle`, and if I dig further I see the underlying error:

```
{
    errorSubCode: 'GEN',
    systemName: 'HATA',
    functionName: 'remoteStart',
    errorSubMessage: 'HATA remoteStart service failed while performing the operation RemoteStart',
    errorMessage: "We're sorry, but we could not complete your request. Please try again later.",
    errorCode: 502,
    serviceName: 'RemoteStart'
}
```

**Usefull info:**
 - OS: macOS
 - Bluelinky Version 7.6.2
 - Region: US
 - Brand: Hyundai

**Additional context**
I'm able to trigger remote start from the app and website fine (though when inspecting the website traffic, I noticed they are using a different API endpoint entirely).

**Comment by Hacksore** [comment]
@SteffeyDev can you share your start code?

**Comment by SteffeyDev** [comment]
Yes, I copied the example from the README for testing:
```js
      const response = await vehicle.start({
        airCtrl: false,
        heating1: true,
        defrost: false,
        airTempvalue: 76,
        igniOnDuration: 15
      });
```

**Comment by Hacksore** [comment]
@SteffeyDev you might want to try `igniOnDuration: 10`, I believe 15 is over the limit causing the 502 on their API.

**Comment by SteffeyDev** [comment]
That did it! Thanks for the help, might be worth adding to the docs so that future people don't make the same mistake 👍🏻

**Comment by Hacksore** [comment]
@SteffeyDev 

It does have a blurb here saying max 10 but not sure if you saw that.

https://bluelinky.readme.io/reference/start

**Comment by SteffeyDev** [comment]
Wow I am blind, sorry to bother!

**Comment by Hacksore** [comment]
Issues still help people find via searches so no worries at all.

I highly doubt that every region is 10 minutes max engine runtime as that would imply Hyundai/Kia/Genesis has consistency in their APIs 😬.
