### ISSUE TITLE
Login without changing the language?

### ISSUE THREAD

**Issue by andig** [Hacksore/bluelinky#208]
Not a bluelinky question, but related to the login flow: evcc user complained that login changes the language: https://github.com/evcc-io/evcc/issues/2578. Is it possible to complete login without forcing a specific language?

**Comment by neoPix** [comment]
Hi @andig,

When login in EU we use this line to set the language and initiate the login process : https://github.com/Hacksore/bluelinky/blob/d085c5eccdd5d3edda29451796b1bb37bd4e35b5/src/controllers/authStrategies/authStrategy.ts#L15

As a matter of fact, the language you use here is applied to your account after the logon, and finally used in the app.

**Comment by andig** [comment]
Yes, thought so. Apparently there's not way to *get* the user#s language upfront to avoid overriding it :(

**Comment by neoPix** [comment]
Did not found a way yet to do so.
If you don't do it, it wil default to:
