### ISSUE TITLE
EU / Hyundai 12V batSoc: 255

### ISSUE THREAD

**Issue by nhet** [Hacksore/bluelinky#210]
Since a while the interface has been getting the value 255 for the 'batSoc' attribute of the 12V battery.

**Comment by PierreLevres** [comment]
Whats does you phone app say? Is the battery icon still green? 
Is all other data recent?

**Comment by nhet** [comment]
Hello @PierreLevres ,
Since I while, may be at the same time with value 255, I don't see the battery icon any more in the app (android).

**Comment by PierreLevres** [comment]
Then I think this is not a bluelinky issue, but related to your car; is your car still OK?
Did you try to log off and logon tho the app, and also in your bluelinky implementation?

**Comment by nhet** [comment]
@PierreLevres, yes the car is OK. I did log off and logon to the app, too. Nothing change. The battery icon is still not shown.

**Comment by PierreLevres** [comment]
Strange. If a reset of the head unit doesn't work (paperclip into the hole next to the volume button), then I think you should bring it in for service.

**Comment by mpucherSmIT** [comment]
Hi there, 

I also get 255 quite some time. In the screenshot the battery has been charged externaly after failing (again). But then at some point it goes back to normal % values. 

Does 255 have some meaing?

![image](https://user-images.githubusercontent.com/38916244/162897195-da59986a-c18a-4421-8627-7f62001316cc.png)
