### ISSUE TITLE
What does batState mean?

### ISSUE THREAD

**Issue by pakerfeldt** [Hacksore/bluelinky#211]
**Question**

Can someone tell me what battery.batState is meant to indicate? I have noticed on my Ioniq 5 that when batState is 1, batSoc is never set. This refers to the 12V auxillary battery.

Thanks!

**Comment by pakerfeldt** [comment]
My current guess is that it means 12V battery is being charged from the big battery but would love to get that confirmed.

**Comment by PierreLevres** [comment]
My guess was that BatState relates to the Battery State icon as shown in the App. Batstate = 0 is Normal. 1 = caution  (orange) What does your app show when batstate = 1 ? Is the indicator light on the car showing the 12V battery is being charged from the big battery when bat state = 1 ?

**Comment by pakerfeldt** [comment]
Trying to look for that icon in the app but can't find it? However, I don't think it relates to caution. It more or less always set to 1 as soon as I connect my car to the charge box (even though the car doesn't necessarily charge).

**Comment by PierreLevres** [comment]
It is the only api output which could be used by the app for this icon.

**Comment by pakerfeldt** [comment]
> It is the only api output which could be used by the app for this icon.
> […](#)
> Op 17 apr. 2022 om 21:36 heeft Patrik Åkerfeldt ***@***.***> het volgende geschreven: ﻿ Trying to look for that icon in the app but can't find it? However, I don't think it relates to caution. It more or less always set to 1 as soon as I connect my car to the charge box (even though the car doesn't necessarily charge). — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

I disagree. It's more likely that they look for when batSoc is less than batSignalReferenceValue (which for me is 65 right now) and use that to trigger the caution icon.

**Comment by PierreLevres** [comment]
Couuld very well be true… But not willing to experiment here!

**Comment by pakerfeldt** [comment]
I mean, voltage is just fine and stable on my 12V battery. The batState highly correlates to turning the engine on and connecting the charge cable. I’ve never seen the caution warning in the app. I’m very certain it has nothing to do with that. Just need to figure out what it means still.

**Comment by Hacksore** [comment]
Continued discussion is welcomed in discord or GitHub discussions.
