### ISSUE TITLE
Location no longer works

### ISSUE THREAD

**Issue by Jens5395** [Hacksore/bluelinky#216]
About a week to ten days ago, my automation to locate my Hyundai Kona broke and has not worked since. I am in Canada and use bluelinky 0.0.27
In ny node red test flow I set up. I use only three nodes - inject time stamp, car location and Msg for a debug output. When I inject the time stamp, the msg output is " payload: "error: TypeError: Cannot read properties of undefined (reading 'result')"
I have a separate automation to log into the Hyundai server on a daily basis but I have also tried login in separately with no change in outcome. If I replace the 'car location' node with a 'status' node, I get a proper message output which seems to indicate that the login works properly.There was never a change in anything between things working and things no longer working.
What can I do to get my node red location automation to work again?

**Comment by Hacksore** [comment]
Might try latest version to see if this is resolved if not please raise a new issue.
