### ISSUE TITLE
Is the documentation up to date on supported features?

### ISSUE THREAD

**Issue by piejanssens** [Hacksore/bluelinky#220]
I saw some issues with reference to code about climate controls, but I don't see that in the documentation.

P.S. Is there any hope on controlling features that are not exposed in the app because of a region lock? For example, in some regions it's possible to remotely control climate of a Kia Sorento PHEV, but Europe this is not. ==> "Vehicle is not EV" 😞

**Comment by Hacksore** [comment]
The docs might be outdated for sure but can you share what you might be trying to run in your code.

**Comment by filmgeek47** [comment]
Not sure if this is a blue-linky problem, but I'm running the home bridge plugin that leverages bluelinky for its calls. On my Ioniq 5 EV, lock/unlock work great, but the climate start won't work no matter what I do.

**Comment by Hacksore** [comment]
@filmgeek47 could you open a new issue with the payload you are using and if you can debug logs?
