### ISSUE TITLE
Does this support a hyundai car in Vietnam

### ISSUE THREAD

**Issue by Vy-CES** [Hacksore/bluelinky#222]
Hi @Hacksore , I am interested in installing this plugin into my car (Hyundai Accent 2021) in Vietnam, is it possible?

**Comment by Hacksore** [comment]
@Vy-CES It sounds like it could be a totally new region which we don't have support for.

It takes a good deal of effort to reverse engineer the mobile app but that's where someone has to start.

**Comment by Vy-CES** [comment]
Well if someone has to start, I guess I can do it and contribute back to the repository. 

Is it possible that you can share me the steps from scratch? @Hacksore

**Comment by Hacksore** [comment]
@Vy-CES this doc is was what I created back in the day.

While it's not likely to be completely irrelevant there have been some security techniques we've seen in certain regions that will require more steps making it hard to reverse.

https://docs.google.com/document/d/1q0Pz2t5Gmt-vv8z-2Yswhvg2x9B2f3d1vjpkIjt9EfQ/edit

**Comment by Hacksore** [comment]
Closing until more info is provided via this issue or a PR.
