### ISSUE TITLE
Does not work with Nextjs deployed on Vercel

### ISSUE THREAD

**Issue by Hanrider8** [Hacksore/bluelinky#226]
**Describe the bug**
I am trying to use bluelinky on vercel via api functions but getting error : `ENOENT: no such file or directory, open '/var/task/node_modules/push-receiver/src/gcm/android_checkin.proto'`

**Usefull info(please complete the following information):**
 - OS: [Do not know what Vercel has]
 - Bluelinky Version [v7.6.6]
 - Region: [EU] 
 - Brand: [kia, hyundai]

**Additional context**
Everything works on localhost and also on heroku. Just Vercel seems like problem.

**Comment by Hacksore** [comment]
I tried a simple demo and seemed to work fine on my end. 

Would you be able to create a demo repo of the issue and I can take a look?

**Comment by Hanrider8** [comment]
What version of nodejs are you running on Vercel ? 
Do you have it on pages/api/{route} on nextJS ? 

Sure I will create demo repo. @Hacksore

**Comment by Hanrider8** [comment]
Soo here is repo [demo repo](https://github.com/Hanrider8/bluelinky-vercel/blob/main/pages/api/odometer.ts) 

Credentials I have in this form `BLUELINK_CREDENTIALS={"proceed":{"cred":{"username":"usr","password":"pass","brand":"kia","region":"EU","pin":"pin"},"vim":"vim"}}` 

Here is link to my vercel where is repo deployed with endpoint [https://bluelinky-vercel-gaur.vercel.app/api/odometer?id=proceed](https://bluelinky-vercel-gaur.vercel.app/api/odometer?id=proceed) @Hacksore

**Comment by Hanrider8** [comment]
Hello, any news? @Hacksore

**Comment by Hacksore** [comment]
@Hanrider8 so I created a fork of your just to try and I can't seem to rerpro that same error.

https://github.com/Hacksore/bluelinky-vercel/tree/simple-test
https://bluelinky-vercel.vercel.app/api/odometer

Keep in mind I don't have an account to replicate with vehicles so maybe that has something to do with it.

Does it only happen when you create a vehicle instance and call odometer?

**Comment by Hanrider8** [comment]
yes yes, during build time or runtime there are  no errors. Only after instance call.

**Comment by Hacksore** [comment]
Yeah that is very strange. Are you using `npm` or `yarn` on the install stage within vercel?

Also what version of node are you using, worked for my on 16.x?

**Comment by Hanrider8** [comment]
it seems like all serverless hosting providers have same issue and also it seems like problem is with one dependency.

**Comment by Hacksore** [comment]
If want to raise an upstream issue to the affected module that could possibly help.

**Comment by Hacksore** [comment]
@Hanrider8 you might be able to see if a demo repo with just `push-receiver` has issues deployed to vercel or other providers as just a simple project that uses it somehow.

**Comment by Hanrider8** [comment]
I will try that.

**Comment by Hacksore** [comment]
Let me know if this is still an issue, going to close for now.
