### ISSUE TITLE
No fetchting of the location

### ISSUE THREAD

**Issue by moses19850** [Hacksore/bluelinky#239]
When I run debug and use the locate function, I receive an error message:

    host: undefined, hostname: 'prd.eu-ccapi.hyundai.com', method: 'GET', path: '/api/v2/spa/vehicles/XXXXXXXXX/location', socketPath: undefined, protocol: 'https:', url: 'https://prd.eu-ccapi.hyundai.com:8080/api/v2/spa/vehicles/XXXXXXXXXXXX/location', gotOptions: { path: '/api/v2/spa/vehicles/XXXXXXXXXXX/location', protocol: 'https:', hostname: 'prd.eu-ccapi.hyundai.com', hash: '', search: '', pathname: '/api/v2/spa/vehicles/XXXXXXXXXXXXXXX/location', href: 'https://prd.eu-ccapi.hyundai.com:8080/api/v2/spa/vehicles/XXXXXXXXX/location', port: 8080, retry: [Object], headers: [Object], hooks: [Object], decompress: true, throwHttpErrors: true, followRedirect: true, stream: false, form: false, json: true, cache: false, useElectronNet: false, baseUrl: [Getter/Setter], method: 'GET' }, statusCode: 400, statusMessage: 'Bad Request', headers: { 'content-type': 'application/json; charset=utf-8', date: 'Tue, 14 Feb 2023 12:20:00 GMT', etag: 'W/"XXXXXXX"', 'x-ratelimit-limit': '100', 'x-ratelimit-remaining': '100', 'x-ratelimit-reset': '1673773057', 'content-length': '128', connection: 'close', 'set-cookie': [Array] }, body: { retCode: 'F', resCode: '4004', resMsg: 'Duplicate request - Duplicate request', msgId: 'XXXXXXXXX' } } }

Can somebody help me with this error?

Thanks

**Comment by PierreLevres** [comment]
It seems all calls fetching data from the car directly are failing at the moment. Also status with refresh flag set to true.
________________________________
Van: moses19850 ***@***.***>
Verzonden: Sunday, February 26, 2023 11:05:37 AM
Aan: Hacksore/bluelinky ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [Hacksore/bluelinky] No fetchting of the location (Issue #239)


When I run debug and use the locate function, I receive an error message:

host: undefined, hostname: 'prd.eu-ccapi.hyundai.com', method: 'GET', path: '/api/v2/spa/vehicles/XXXXXXXXX/location', socketPath: undefined, protocol: 'https:', url: 'https://prd.eu-ccapi.hyundai.com:8080/api/v2/spa/vehicles/XXXXXXXXXXXX/location', gotOptions: { path: '/api/v2/spa/vehicles/XXXXXXXXXXX/location', protocol: 'https:', hostname: 'prd.eu-ccapi.hyundai.com', hash: '', search: '', pathname: '/api/v2/spa/vehicles/XXXXXXXXXXXXXXX/location', href: 'https://prd.eu-ccapi.hyundai.com:8080/api/v2/spa/vehicles/XXXXXXXXX/location', port: 8080, retry: [Object], headers: [Object], hooks: [Object], decompress: true, throwHttpErrors: true, followRedirect: true, stream: false, form: false, json: true, cache: false, useElectronNet: false, baseUrl: [Getter/Setter], method: 'GET' }, statusCode: 400, statusMessage: 'Bad Request', headers: { 'content-type': 'application/json; charset=utf-8', date: 'Tue, 14 Feb 2023 12:20:00 GMT', etag: 'W/"XXXXXXX"', 'x-ratelimit-limit': '100', 'x-ratelimit-remaining': '100', 'x-ratelimit-reset': '1673773057', 'content-length': '128', connection: 'close', 'set-cookie': [Array] }, body: { retCode: 'F', resCode: '4004', resMsg: 'Duplicate request - Duplicate request', msgId: 'XXXXXXXXX' } } }


Can somebody help me with this error?

Thanks

**Comment by dest4** [comment]
A duplicate request error seems to appear when too many concurrent requests are sent to the servers. Consider doing your calls sequentially and not concurrently.
