### ISSUE TITLE
error code 4003

### ISSUE THREAD

**Issue by VolkerK62** [Hacksore/bluelinky#240]
Login error Kia/Hyundai in Region EU
log file see https://github.com/evcc-io/evcc/issues/7227

Additional Info:
Login error also with "node-red-contrib-bluelinky"

**Comment by tobiasbayer** [comment]
Seems that Hyundai/Kia intentionally broke the login process: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/issues/309
