### ISSUE TITLE
[question]: is "cache" vs "refresh" device dependend?

### ISSUE THREAD

**Issue by binderth** [Hacksore/bluelinky#246]
**Describe the behaviour**
I'm using my Kia EV6 as a "moving battery" for my other EV, so I can charge that over night with my EV6-V2L adapter. 
After current issues with completely wracking the 12V battery I only "refresh" with bluelinky if my wallbox starts charging. that way I'm sure to only directly go through to the car, if it's already "awake". Apart from a "refresh" with wallbox charging I do a "cache"-request every 15mins to keep my smarthome up to date on the cars SoC, location, status of doors/windows etc.

So I'm experiencing the following behaviour:

1. deplete SoC of EV6 while driving => Kia-App gets updated *and* the cache of bluelinky-queries gets updated
2. deplete SoC of EV6 while standing => Kia-App gets updated, but *not* the cache of bluelinky-queries

So my question is: Is the caching device dependend? meaning the Kia-App gets "its own" cache and bluelinky as "the other Kia-App?" gets also its own? that would explain the App showing 73% now and bluelinky still showing 98%.

**Usefull info(please complete the following information):**
 - OS: Dockerized node-red
 - Bluelinky Version node-red-contrib-bluelinky 0.0.30 -> with bluelinky v8.1.0
 - Region: EU
 - Brand: kia

**Additional context**
What that means is at first glance just an inconvenience, but if the SoC drops below 80% this leads to some logical errors within my whole smarthome environment. So e.g. yesterday i came home with 98% SoC and charged my other EV via V2L and the SoC dropped to 73%. So my smarthome still thinks: "hey it's almost full" and does not trigger charging. And only with charging I'm currently updating *actively* the SoC.

**Comment by PierreLevres** [comment]
Does the kia app get updated by itself? Or do you press the circular arrow?
Do you use the same user account in both the Kia app and in your bluelinky configuration?

Afaik it is the same cache.

**Comment by binderth** [comment]
Ran into the Authentication problem solved with v8.1.1

I tested it right now:

1. got the "last updated: 01.07. 16:57" in the App
2. got "20230701125757" as vehicleStatus.time

then reloaded in the App

3. got "Last updated: 04.07 12:51" in the App
4. got "20230704085111" as vehicleStatus.time

So it's safe to say, the same credentials at least get the same information. So I have to look elsewhere in my script to solve the problem.


and yes, same user for App and Bluelinky. and the App only updates itself, if the car is charging - or running. The App never gets updated, if the car is discharging or parked without charging.

**Comment by PierreLevres** [comment]
I have same experience. the cache does not seem to be refreshed. Seems to be a result of the firmware update I did last week. My kia app also has old data at this moment. So not a bluelinky issue but a Kia/Hyundai issue
________________________________
Van: Thomas B. ***@***.***>
Verzonden: Tuesday, July 4, 2023 12:54:37 PM
Aan: Hacksore/bluelinky ***@***.***>
CC: PierreLevres ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [Hacksore/bluelinky] [question]: is "cache" vs "refresh" device dependend? (Issue #246)


Ran into the Authentication problem solved with v8.1.1

I tested it right now:

  1.  got the "last updated: 01.07. 16:57" in the App
  2.  got "20230701125757" as vehicleStatus.time

then reloaded in the App

  1.  got "Last updated: 04.07 12:51" in the App
  2.  got "20230704085111" as vehicleStatus.time

So it's safe to say, the same credentials at least get the same information. So I have to look elsewhere in my script to solve the problem.

and yes, same user for App and Bluelinky. and the App only updates itself, if the car is charging - or running. The App never gets updated, if the car is discharging or parked without charging.
