### ISSUE TITLE
Added new Features to the Plug-in

### ISSUE THREAD

**Issue by carlosgamezvillegas** [Hacksore/bluelinky#247]

**Comment by Hacksore** [comment]
Happy to review a PR for this if you can raise one.

**Comment by carlosgamezvillegas** [comment]
Hello Hacksore,

Unfortunately I made the changes directly in the .js files since I don't know how to use Typescript so I don't think a PR would work.

if you know an easy way to convert .js. to typescript let me know.

Kind regards.
