### ISSUE TITLE
Client Error GotError 

### ISSUE THREAD

**Issue by carlosgamezvillegas** [Hacksore/bluelinky#257]
Hello Bluelinky team,

Since July 17 me and other users have reported having an error when starting Bluelinky. When we start Bluelinky we get the following error:

Client Error GotError [RequestError]: write EPROTO 00FAF1B6:error:0A000152:SSL routines:final_renegotiate:unsafe legacy renegotiation disabled:../deps/openssl/openssl/ssl/statem/extensions.c:922:

    at ClientRequest.<anonymous> (/var/lib/homebridge/node_modules/homebridge-hyundai-bluelink/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (node:events:629:26)
    at ClientRequest.emit (node:events:526:35)
    at ClientRequest.origin.emit (/var/lib/homebridge/node_modules/homebridge-hyundai-bluelink/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EPROTO',
  host: 'api.telematics.hyundaiusa.com',
  hostname: 'api.telematics.hyundaiusa.com',
  method: 'POST',
  path: '/v2/ac/oauth/token',
  socketPath: undefined,
  protocol: 'https:',
  url: 'https://api.telematics.hyundaiusa.com/v2/ac/oauth/token',
  gotOptions: {
    path: '/v2/ac/oauth/token',
    protocol: 'https:',
    slashes: true,
    auth: null,
    host: 'api.telematics.hyundaiusa.com',
    port: null,
    hostname: 'api.telematics.hyundaiusa.com',
    hash: null,
    search: null,
    query: null,
    pathname: '/v2/ac/oauth/token',
    href: 'https://api.telematics.hyundaiusa.com/v2/ac/oauth/token',
    retry: {
      retries: [Function (anonymous)],
      methods: [Set],
      statusCodes: [Set],
      errorCodes: [Set]
    },
    headers: {
      'user-agent': 'PostmanRuntime/7.26.10',
      client_id: 'xxxxxxxxxxxxx',
      client_secret: 'xxxxxxxxxxx',
      accept: 'application/json',
      'accept-encoding': 'gzip, deflate',
      'content-type': 'application/json',
      'content-length': 68
    },
    hooks: {
      beforeRequest: [],
      beforeRedirect: [],
      beforeRetry: [],
      afterResponse: [],
      beforeError: [],
      init: []
    },
    decompress: true,
    throwHttpErrors: true,
    followRedirect: true,
    stream: false,
    form: false,
    json: true,
    cache: false,
    useElectronNet: false,
    method: 'POST',
    body: '{"username":"XXXXXXXX","password":"XXXXXX"}'
  }
}

**Usefull info(please complete the following information):**
 - OS: Raspbian (Homebridge)
 - Bluelinky Version 7.5.0 and I also tried 8.1.1 with the same error in both
 - Region: US,
 - Brand: Hyundai

**Additional context**
Bluelinky is use in the Homebridge Bluelinky Plugin and I was able to trace the error given by one of the Bluelinky dependencies which I believe is "got".

Please let me know if this is something that your team can help with.

Kind regards,

Carlos

**Comment by Hacksore** [comment]
probably related to https://github.com/Hacksore/bluelinky/issues/254

**Comment by carlosgamezvillegas** [comment]
Thank you! This solved my issue and communicated the workaround to the Homebridge Bluelinky users.

**Comment by cmorozcogmailcom** [comment]
how was this issue solved?

**Comment by Hacksore** [comment]
@cmorozcogmailcom this PR is going to solve it once we get it merged #275
