### ISSUE TITLE
AppID's changed again?

### ISSUE THREAD

**Issue by cuetus** [Hacksore/bluelinky#259]
Invalid request value - Invalid Application Id.

**Comment by larsmeldgaard** [comment]
> Invalid request value - Invalid Application Id.

I get this error as well. Can someone explain what it is about and how to fix it?

**Comment by mclane** [comment]
same problem exists with Kia

**Comment by PierreLevres** [comment]
The central stamps  were not refreshed for two days. So that is probably the cause. Op 29 jul. 2023 om 11:39 heeft mclane ***@***.***> het volgende geschreven:﻿
same problem exists with Kia

**Comment by cuetus** [comment]
> The central stamps  were not refreshed for two days. So that is probably the cause. Op 29 jul. 2023 om 11:39 heeft mclane ***@***.***> het volgende geschreven:﻿ same problem exists with Kia —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Issue still exists.

**Comment by cuetus** [comment]
Anyone managed to generate stamps who'd like to share? Can't get the docker container to compile, maven clean fails, exit code 159. Can't get the docker.io hacksore/hks:arm to run in ARM (RPI), it just exits, also with exit code 159

**Comment by andig** [comment]
@cuetus see https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/371 for how it's done.

**Comment by cuetus** [comment]
neoPix found the solutions, stamps updating again.
