### ISSUE TITLE
npm run debug fails with type script error

### ISSUE THREAD

**Issue by snowball77** [Hacksore/bluelinky#265]
**Describe the bug**
I checked out master and ran 
`npm run debug`:

> bluelinky@8.2.1 debug
> cross-env LOG_LEVEL=debug ts-node debug.ts

/Users/snowball/git/bluelinky/node_modules/ts-node/src/index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
debug.ts:34:34 - error TS2339: Property 'useInfo' does not exist on type '{ username: string; password: string; pin: string; brand: string; or: any; hyundai: any; vin: string; }'.

34 const { username, password, pin, useInfo = false } = config;

After removing this property there had been more positions where this property needed to be removed. I removed all, then it worked.

**Usefull info(please complete the following information):**
 - OS: [e.g. macOS, Windows, Linux] macos
 - Bluelinky Version [e.g. v5.2.3] master
 - Region: [e.g. US, CA, EU] EU
 - Brand: [kia, hyundai] kia

**Comment by snowball77** [comment]
The followup errors are:
```
❯ npm run debug

> bluelinky@8.2.1 debug
> cross-env LOG_LEVEL=debug ts-node debug.ts


/Users/snowball/git/bluelinky/node_modules/ts-node/src/index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
debug.ts:125:11 - error TS18004: No value exists in scope for the shorthand property 'useInfo'. Either declare one or provide an initializer.

125           useInfo,
              ~~~~~~~
debug.ts:133:11 - error TS18004: No value exists in scope for the shorthand property 'useInfo'. Either declare one or provide an initializer.

133           useInfo,
              ~~~~~~~
debug.ts:141:11 - error TS18004: No value exists in scope for the shorthand property 'useInfo'. Either declare one or provide an initializer.

141           useInfo,
              ~~~~~~~
debug.ts:149:11 - error TS18004: No value exists in scope for the shorthand property 'useInfo'. Either declare one or provide an initializer.

149           useInfo,
              ~~~~~~~
debug.ts:157:11 - error TS18004: No value exists in scope for the shorthand property 'useInfo'. Either declare one or provide an initializer.

157           useInfo,
              ~~~~~~~

    at createTSError (/Users/snowball/git/bluelinky/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/Users/snowball/git/bluelinky/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/Users/snowball/git/bluelinky/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/Users/snowball/git/bluelinky/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/Users/snowball/git/bluelinky/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/snowball/git/bluelinky/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
```

**Comment by snowball77** [comment]
I created a pull request removing the non-existing property. Please check whether this is the right way of fixing it

**Comment by Hacksore** [comment]
I think for now a better option is to just add this to your `config.json` and the error should go away.
```
"useInfo": false
```

**Comment by snowball77** [comment]
> I think for now a better option is to just add this to your `config.json` and the error should go away.
> 
> ```
> 
> "useInfo": false
> 
> ```

Fair enough, but then it would be good to update the example file given on the webpage in the Readme.
