### ISSUE TITLE
Node Red shows ERROR

### ISSUE THREAD

**Issue by VolkerK62** [Hacksore/bluelinky#270]
Since this afternoon, Bluelinky Node Red (Hyundai) isn´t working anymore.
Nothing had bee changed.
![image](https://github.com/Hacksore/bluelinky/assets/99199865/da358cd8-6842-4223-9fef-d69f143e10dd)

**Comment by PierreLevres** [comment]
Yesterday I had one failed call at 12:24, (service unavailable) and one failed call at 16:09 (unauthorized on GET). 

It happens every now and then. In my node red flow I do an automatic login after an 'unauthorized' error.

**Comment by VolkerK62** [comment]
today everything is working fine again. So only server problems and no API changes
Merry x-mas
