### ISSUE TITLE
Problems executing the given JS example

### ISSUE THREAD

**Issue by niklas85** [Hacksore/bluelinky#279]
**Describe the bug**
I have problems executing the given JS example. I have set up a .js-File by copy&paste the code of the example.
If I try to execute it with "~$ node myFile.js" I receive a TypeError:

```
const client = new BlueLinky({
               ^

TypeError: BlueLinky is not a constructor
    at Object.<anonymous> (/home/niklasm/executeBluelinky.js:5:16)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49
```

Before executing I have installed node.js in Version 20.12.2 and npm in Version 10.5.0 and bluelinky in version 8.3.1 as well.
I'm sorry, but I'm not familiar with JS. But I'm expecting your example to work.
Maybe its a tiny thing that has changed in your code since you wrote the example. Or maybe I'm to stupid to understand. I'll be very happy to receive some help.

**Usefull info(please complete the following information):**
 - OS: Linux
 - Bluelinky Version 8.3.1
 - Region: [EU] 
 - Brand: [kia]

**Comment by Hacksore** [comment]
There seems to have been some breaking change that slipped through I guess. 

try this to import the class, this same thing was reported on the discord as well.

```
const { BlueLinky } = require('bluelinky');
```

**Comment by niklas85** [comment]
Many thanks, now it's working!
