### ISSUE TITLE
HTTPError: Response code 401 (Authorization Required)

### ISSUE THREAD

**Issue by justinoreilly** [Hacksore/bluelinky#33]
Attempting to configure a flow to get status and receive "HTTPError: Response code 401 (Authorization Required)" as a debug output. This is the US region. 
 
<img width="621" alt="Screen Shot 2020-05-14 at 11 18 29 AM" src="https://user-images.githubusercontent.com/7625409/81952607-ae69dc00-95d4-11ea-8775-c8d54aa2d934.png">
<img width="473" alt="Screen Shot 2020-05-14 at 11 19 06 AM" src="https://user-images.githubusercontent.com/7625409/81952661-bfb2e880-95d4-11ea-8c3b-15f262f0b88e.png">

**Comment by SondreNjaastad** [comment]
Please move this issue to the node red library itself
https://github.com/SondreNjaastad/node-red-contrib-bluelinky

**Comment by justinoreilly** [comment]
Issue Moved: https://github.com/SondreNjaastad/node-red-contrib-bluelinky/issues/4
