### ISSUE TITLE
Update Status for EU

### ISSUE THREAD

**Issue by Amxt** [Hacksore/bluelinky#42]
I noticed that for Canada and America the 'status' can be refreshed/updated but for Europe this only gets the last known status without updating it. Is there a reason for this? It would be really useful to be able to refresh the status for Europe too. 
 
Calling ${EU_BASE_URL}/api/v2/spa/vehicles/${this.config.id}/status seems to do it.

**Comment by SondreNjaastad** [comment]
The /status endpoints is always the latest status as far as i know? Have not experienced it being the same. US and EU APIs are very different

**Comment by Amxt** [comment]
Right now to get the status only the /status/latest endpoint is being called (europianVehicle line 185). This seems to return stale data. From my limited testing, it looks like you have to call the /status endpoint first and then the /status/latest endpoint will return the updated status.

**Comment by Hacksore** [comment]
So I think we have some inconsistencies as for the US we can pass a should update flag to `status()`.

https://github.com/Hacksore/bluelinky/blob/953235d76136dd7c333a0686dbec205041a6fbe5/lib/vehicles/americanVehicle.ts#L158

**Comment by altagir** [comment]
I originally put the status(refresh) since in canada, we have 2 different endpoint

- status(false)will just poll the hyundai server (fast) and get their latest data, which is often wrong
- status(true) will ask data from the car (and update hyundai server info)

In most cases, I only want the fetched data from the car itself

**Comment by Amxt** [comment]
Something similar could be done for the EU where if refresh = true is set then the /status endpoint is called, if it's set to false then /status/latest is called. The /status/latest endpoint returns the cached status.

**Comment by Hacksore** [comment]
I agree @Amxt we do need to support this for consistency's sake. 

Still not sure how @SondreNjaastad didn't notice this as he has a dashboard setup that has info about his vehicle.

**Comment by SondreNjaastad** [comment]
The car is in use several times a day. Maybe it update on start/stop?

**Comment by Amxt** [comment]
That may be the case, unfortunately I don't have a Hyundai car to test on. Some car API's do update status either periodically (e.g. Renault) or triggered by certain events taking place such as start/stop (e.g. BMW). The /status endpoint seems to force an immediate status update.

**Comment by tiramiseb** [comment]
Hello,

I am in the process of buying a Hyundai Ioniq Electric. I live in France.

I have tested the car this weekend. I have stopped the car yesterday, plugged it into my OpenEVSE.

When testing Bluelinky this morning, I only got data from yesterday (car not fully charged, etc).

After driving the car back to the shop, I tried Bluelinky again (the car is still connected to my Bluelink account, because I will by this exact car, just waiting for the bank to provide the money). Now, I get data from when I parked the car in front of the shop.

**Comment by Hacksore** [comment]
@tiramiseb Welcome! 
Glad to have more people actively using the lib. Seems we do need to ensure we are able to make soft (cached) and hard (query car) status requests based on the developer's needs.

Part of v5.0.0 is us trying to refactor a lot of the internals so this can be covered with that I'd imagine.

As pointed out by @Amxt we might have to make two requests to force the car to update.

**Comment by SondreNjaastad** [comment]
I Will try to fix this tomorrow

**Comment by SondreNjaastad** [comment]
Also, @tiramiseb, more EU cars are very welcome! 😊

**Comment by tiramiseb** [comment]
This car will be very welcome in my family too :joy: 

For the record, I first had a ZOE, I hacked their app's protocol only for fun, and disassembled one of the two car keys to directly wire the "open charging hatch" and the "enable AC" buttons to my home automation setup.
I then bought a Soul EV, but in Europe Kia does not provide any connectivity in Europe for this vehicle. That was no fun :smile: 
The Ioniq's key does not have buttons for AC nor charging hatch, but at least I can use the app's protocol for AC :wink:

**Comment by SondreNjaastad** [comment]
I own a 2020 Ioniq myself, rly  a shame that you can't open the charing hatch for the key or the app! I have made tested some more localy today, and as we thought, the status does update if we do a call to status instead of status/latest. I will make a PR for this into dev

**Comment by cathiele** [comment]
i created a pull-request for this https://github.com/Hacksore/bluelinky/pull/46 maybe this helps with this issue

**Comment by SondreNjaastad** [comment]
Sorry, i forgot there was an open issue for this. This was solved in PR #45

**Comment by SondreNjaastad** [comment]
Solved in PR #45

**Comment by SondreNjaastad** [comment]
This issue will appear in v5. Currently available as bluelinky@next
