### ISSUE TITLE
develop-branch: EU vehicle.location() timeout

### ISSUE THREAD

**Issue by cathiele** [Hacksore/bluelinky#47]
I updated to the bluelinky@next version and now i don't get the location of the car. 

In the master-Branch the location is extracted from the status-request, in the develop-branch it is requested via the .../location-endpoint of the API.

The request to the location-endpoint ends with a timeout in my case. (car inside, no gps-available if this is important)

The status request with {refresh: true} is working, so in general there is a connection to the car possible at the moment of the request.

For now i will switch to the master branch to get the location info back.

car: 2020 Kona 64kWh, EU-Endpoint

**Comment by SondreNjaastad** [comment]
The latest endpoint gets the last known location. The new way requests the position from the car. We should handle the timeouts, but its rather a design choice. Should we return /latest if /location times out?

**Comment by cathiele** [comment]
it would be nice to have access to all the data that is returned by the status/latest endpoint, and additionally the explicit /location-request. (something like the {refresh:true|false} for the status-request. 

In my case the timeout is very long (maybe a minute?) , so i would for now in general prefer the /status/latest data.

what is the difference off the location data from the /status endpoint and the /location-endpoint?

**Comment by Hacksore** [comment]
ping @SondreNjaastad 

Didn't you have a fix in the works for this?

**Comment by plips-nl** [comment]
Not an answer to the location and timeout question, but I agree with @cathiele .. An API call that returns ALL (raw) data from the /status/latest endpoint would come in handy, as an addition to the formatted subset with the same data as /status returns.  

The Kia/Hyundai servers treat location, odometer and vehicle status in different ways. That makes it really hard to understand when which data is returned.

**Comment by Hacksore** [comment]
I'm not sure this is an issue anymore so I'll close it. If there is anything we can improve a new issue can be raised to track the effort.
