### ISSUE TITLE
Support for UK Hyundai 2020 Cars

### ISSUE THREAD

**Issue by mazshar** [Hacksore/bluelinky#48]
Thank you for working on this brilliant wrapper library.

Any chance we can get something similar here in the UK?

The base url is 'http://prd.eu-ccapi.hyundai.com'. I have access to URI resources for each function which I can share but struggling with the authentication process.

**Comment by SondreNjaastad** [comment]
Have you tried the EU config? Looks like the same URL. Working on my Norwegian 2020 Ioniq Electric

**Comment by mazshar** [comment]
> 
> 
> Have you tried the EU config? Looks like the same URL. Working on my Norwegian 2020 Ioniq Electric

Yes you're right! That's fantastic. I've been waiting for this since I got the car in December

**Comment by SondreNjaastad** [comment]
Closing this then 😊

**Comment by mazshar** [comment]
@SondreNjaastad I'm currently getting errors when trying to log in using the EU config. I get an unhandled promise rejection error. Has something changed with the log in process or am I doing something incorrect? I've built the project using node run-script build and I've created an index.js with the example code using my details. When I run 'node index.js' I get the above error.

**Comment by SondreNjaastad** [comment]
Hi! Hyundai have introduced som breaking changes, we are not sure what and how to fix it yet

**Comment by SondreNjaastad** [comment]
> @SondreNjaastad I'm currently getting errors when trying to log in using the EU config. I get an unhandled promise rejection error. Has something changed with the log in process or am I doing something incorrect? I've built the project using node run-script build and I've created an index.js with the example code using my details. When I run 'node index.js' I get the above error.

Hi! Hyundai have introduced som breaking changes, we are not sure what and how to fix it yet

**Comment by mazshar** [comment]
Okay, previously I’ve been able to decompile the android app, if that helps
at all?

**Comment by SondreNjaastad** [comment]
We have tried to do that again, but we have not found any changes. So i believe its serverside

**Comment by mazshar** [comment]
Thanks for the update. I’m curious, I noticed there were additional
endpoints in the decompiled code e.g. heating seats remotely. Wondering
whether you tried them? I’m guessing they’re blocked serverside

**Comment by plips-nl** [comment]
FWIW in Netherlands (also Europe :) ) play and appstore: 
iPhone apps for Hyundai Bluelink and Kia UVO were not updated recently (3 mnts aho, current ver = 1.4.117 for both)
Android apk versions also nog chnges, both ver 1.4.118 for 3 months. 



groet,

Peter

**Comment by mazshar** [comment]
@SondreNjaastad if there are no changes on the app side then how does it still communicate with the server?

**Comment by SondreNjaastad** [comment]
Hi! This should not be an issue any more, the change was that setting the language was made an requirement, that change has been implemented in the last version

**Comment by mazshar** [comment]
@SondreNjaastad amazing news! Any ideas if we can expand the endpoints to include things like remote heated seats?

**Comment by SondreNjaastad** [comment]
If its included in the app, we probably can. You could make a separate feature request, so if it is not possisble, at least we have a issue showing that 😊

**Comment by mazshar** [comment]
@SondreNjaastad great! Any chance you could provide some additional instructions for node newbies like myself? These are the steps I took so far.

1. Create a directory for project e.g. 'car'
2. In the new directory, run `npm install bluelinky`
3. Create an index.js with the example code including my credentials and car details.
4. Run `node index.js`

I'm well versed in RESTful APIs and Python though. So I would be keen to give you a hand with European updates if you like and once I'm more familiar with node. I can start by helping create some more documentation!
