### ISSUE TITLE
Support for bluelink in Canada

### ISSUE THREAD

**Issue by altagir** [Hacksore/bluelinky#5]
>  const auth = await client.login();

I always get an empty auth here. username and password are correct.
should i enable something to access API ?

Edit: turns out this is related to the same US API service not being compatible with Canada vehicles.

**Comment by Hacksore** [comment]
@altagir So you can log in here without any issues?
https://owners.hyundaiusa.com/us/en/index.html

 I think I need to add some better logging so we can opt-in to more verbose output when debugging.

**Comment by altagir** [comment]
No i can't. But i think you just pinpoint the issue

i bought EV in canada. So i probably dont have account in the hyundaiusa.com website. 

I guess i can change server?

**Comment by Hacksore** [comment]
@altagir Can you please link the site for Canada and I can try and add in support :).

**Comment by altagir** [comment]
unbelievably there is no account creation at hyundaicanada.com , nor there is probably opened api?
i will try to trick US account creation or request directly to canadian side

**Comment by Hacksore** [comment]
@altagir How about this?
https://mybluelink.ca/login

**Comment by altagir** [comment]
this one works perfectly :D

**Comment by altagir** [comment]
this site works well. correct entry for credentials

I see a lot of references to hyundaiusa in code with paths for service. i am unsure api will match on both side.

**Comment by Hacksore** [comment]
@altagir If you are able to fire a lock request off and sniff the web traffic in chrome devtools, I could analyze that and see where it’s going. If there would be an easy way to make this compatible I can surely give it a shot.

If you are sharing that request here make sure to redact anything personal like user specific info.

**Comment by altagir** [comment]
I did that earlier and tried to get a login working
endpoints are very different, it seems also I don't need initial token ? as I don't see it in the stacktrace
I will package the list and send to your email

**Comment by Hacksore** [comment]
All the current changes for this are being done in [support-canada-api](https://github.com/Hacksore/bluelinky/tree/support-canada-api) branch.

It's been a while since I worked on these changes and from what I remember they were working for @altagir.

**Comment by altagir** [comment]
API is working well, there is just the start remote endpoint to finish
I sent pull request to add locate
another on its way for start remote and could be merged then to main

**Comment by Hacksore** [comment]
@altagir New code is merged into master, try your best to incorporate all your previous changes in the new codebase.

Ping me on discord if you need any help along the way.

**Comment by altagir** [comment]
merged into main branch
