### ISSUE TITLE
Not working for EU Kia e-niro 2020 (UVO app)

### ISSUE THREAD

**Issue by gruijter** [Hacksore/bluelinky#52]
Thx for revere engineering the API! I assume that the Hyundai bluelinky API is the same as what Kia UVO connect is using. But I'm not sure :) 

When I try below code, the 'ready' event is never triggered. I only get this log `[2020-07-16 17:20:17] info: { "test": 1}`

```
const client = new BlueLinky({
		username: 'account@mail.com',
		password: 'mySecrtePwd',
		region: 'EU',
		pin: '1234',
	});

	client.on('ready', async () => {
		console.log('READY!!!');
		const vehicle = await client.getVehicles();
		console.log(vehicles);
	});
```

**Comment by Hacksore** [comment]
So basically it is "similar" but is out of the scope of this project. However, there is discussions on the discord about getting it working.

A technical explanation is that there is a different base URL and client ids for it to communicate with the Kia services.

Please look at contributing to either https://github.com/wcomartin/kiauvo or starting a new project entirely for explicit Kia support.

**Comment by gruijter** [comment]
I found the repository for @wcomartin, but first of all I dont know python, and secondly there is an issue there with EU region and william directs to bluelinky :).

https://github.com/wcomartin/kiauvo/issues/1

I am willing to give it a shot in nodejs, but where can I find a description of the API and the authentication process? I tried logging the UVO app communication with man-in-the middle, but the app tunnels directly to kia, and the app doesn't work anymore when I put fiddler in between :( 

Any hints how I can do this?

**Comment by Hacksore** [comment]
Yeah, I really want someone to just copy bluelinky into something new and update to be ready for Kia. 

If we can't get anyone from the community to do this I might do it 😀.

For the RE side of things, I have a document on what I do to get info from apps. Likely what is blocking you right now is SSL pinning which will not let traffic flow through your MITM proxy.

https://docs.google.com/document/d/1q0Pz2t5Gmt-vv8z-2Yswhvg2x9B2f3d1vjpkIjt9EfQ/edit?usp=sharing

**Comment by gruijter** [comment]
Thx for the document. I'm affraid that is beyond my skills at the moment :(. I hope someone else has the skills, time and endurance to create an API wrapper for Kia UVO (like you! 👍 )

**Comment by plips-nl** [comment]
I have both Js and python code for Kia UVO in Europe. All up and running since yesterday. Look at my fork of the development branch. 

Groet,
Peter Lips

**Comment by gruijter** [comment]
Awesome Peter! Will try tonight. (Need to figure out how to build from your fork though)

**Comment by gruijter** [comment]
@plips-nl I need your help in how to use your fork (I'm a noob only able to install with npm). How can I reach you directly?

**Comment by Kreuger** [comment]
@gruijter You can download the file as a zip or use git to copy it to a folder on your computer.

**Comment by gruijter** [comment]
Hi @Kreuger Thx, but in the mean time @plips-nl published it already on npm

https://www.npmjs.com/package/kuvork

**Comment by prodigy7** [comment]
Hm, looking for code access my Kia e-niro 2020 i found this project and this thread. Now, if all is equal and only the servers and client credentials are different, so why don't implement a simple switch? Or i do understand something wrong? It mades sense, if one project are maintained by different developers and code is up to date.

**Comment by plips-nl** [comment]
Maybe eventually this will be the case. But the way it is now, a simple switch won't do. For now, if you are in Europe. you can use the “Kuvork" lib I created. Or create your own. All you have to do is change the lib/constants/europe.ts file.

**Comment by fuatakgun** [comment]
hi all, if you have noticed, there is a different login flow in Kia Uvo for registered users since October 2020. We are not allowed to create a UVO account and we should be using Kia account and this change will break the compatibility of existing libraries.

I am working on reverse engineering the new flow, setup local proxy and hotspot and fixing user certificate issues on Android. but these are just initial steps, I will let you know.

**Comment by PierreLevres** [comment]
Same goes for bluelink Hyundai users maybe? There is some discussion in the node-red-contrib-bluelinky git...

**Comment by andig** [comment]
Hyundai is wfm, Kia is not.

**Comment by PierreLevres** [comment]
WFM?
For me Kia e-Niro 2020 bluelinky 7.0.0 is working perfectly

**Comment by fuatakgun** [comment]
hi all,

I have baked a custom integration for EU Kia Uvo, this will be working for new account types. Thanks for your hard work @wcomartin

Warning ahead; this is pre-alpha phase, please do not expect something fully functional, I will improve the integration by time.

You can install this either manually copying files or using HACS. Configuration can be done on UI, you need to enter your username and password, (I know, translations are missing!). It will only fetch values for the first car, I am not sure if there are people outside using Kia Uvo with multiple cars :)

update - It will fetch the cached information every 30 minutes from Kia Servers. force update - It will ask your car for the latest data every 2 hours. It will not force update between 10PM to 6AM. I am trying to be cautios here.

https://github.com/fuatakgun/kia_uvo
