### ISSUE TITLE
Prepare for simpeler maintenance of Kia UVO EU Fork

### ISSUE THREAD

**Issue by plips-nl** [Hacksore/bluelinky#54]
If you would change the following lines in european.controller.ts and in constants/europe.ts the Kia-port would work by only changing the constants/europe.ts.
That way you don't have to maintain the Kia part, but for maintenance of the fork it is easy, since only europe.ts has to be updated.

The changes I propose underneath have been tested on KiaUVO. Works flawlessly.

**In european.controller.ts**
line1: import { EU_CONSTANTS, EU_BASE_URL, EU_BASE_HOST, EU_CONTENT_LENGTH, EU_CLIENT_ID } from './../constants/europe';
line 102:           'ccsp-service-id': EU_CLIENT_ID,
line 105:           'Host': EU_BASE_HOST,
line 135:          'Content-Length': EU_CONTENT_LENGTH,
line 136:          'Host': EU_BASE_HOST,

**constant file europe.ts would then look like for Hyundai BlueLink**
export const EU_BASE_URL = 'https://prd.eu-ccapi.hyundai.com:8080';
export const EU_BASE_HOST = 'prd.eu-ccapi.hyundai.com:8080';
export const EU_CONTENT_LENGTH = '154'
export const EU_CLIENT_ID = '6d477c38-3ca4-4cf3-9557-2a1929a94654'
export const EU_ENDPOINTS = {
  session: `${EU_BASE_URL}/api/v1/user/oauth2/authorize?response_type=code&state=test&client_id=${EU_CLIENT_ID}&redirect_uri=${EU_BASE_URL}/api/v1/user/oauth2/redirect`,
  login: `${EU_BASE_URL}/api/v1/user/signin`,
  language: `${EU_BASE_URL}/api/v1/user/language`,
  redirectUri: `${EU_BASE_URL}/api/v1/user/oauth2/redirect`,
  token: `${EU_BASE_URL}/api/v1/user/oauth2/token`,
};
export const EU_CONSTANTS = {
  basicToken:
    'Basic NmQ0NzdjMzgtM2NhNC00Y2YzLTk1NTctMmExOTI5YTk0NjU0OktVeTQ5WHhQekxwTHVvSzB4aEJDNzdXNlZYaG10UVI5aVFobUlGampvWTRJcHhzVg==',
  GCMSenderID: '199360397125',
};

**constant file europe.ts would then look like for KIA**
export const EU_BASE_URL = 'https://prd.eu-ccapi.kia.com:8080';
export const EU_BASE_HOST = 'prd.eu-ccapi.kia.com:8080';
export const EU_CONTENT_LENGTH = '150'
export const EU_CLIENT_ID = 'fdc85c00-0a2f-4c64-bcb4-2cfb1500730a'
export const EU_ENDPOINTS = {
  session: `${EU_BASE_URL}/api/v1/user/oauth2/authorize?response_type=code&state=test&client_id=${EU_CLIENT_ID}&redirect_uri=${EU_BASE_URL}/api/v1/user/oauth2/redirect`,
  login: `${EU_BASE_URL}/api/v1/user/signin`,
  language: `${EU_BASE_URL}/api/v1/user/language`,
  redirectUri: `${EU_BASE_URL}/api/v1/user/oauth2/redirect`,
  token: `${EU_BASE_URL}/api/v1/user/oauth2/token`,
};
export const EU_CONSTANTS = {
  basicToken:
    'Basic ZmRjODVjMDAtMGEyZi00YzY0LWJjYjQtMmNmYjE1MDA3MzBhOnNlY3JldA==',
  GCMSenderID: '199360397125',
};

**Comment by Hacksore** [comment]
This is helpful for others looking into the Kia side. For now, we can keep the code focused on https://github.com/plips-nl/Kuvork.
