### ISSUE TITLE
Error: temperature out of bounds! min: 15.0* max: 30*, max step: 0.5

### ISSUE THREAD

**Issue by cathiele** [Hacksore/bluelinky#55]
With Version 5.1.0 i get the error:

`Error: temperature out of bounds! min: 15.0* max: 30*, max step: 0.5`

the value passed to the function is "00H"

Car: EU Kona 64kwh MY2020

**Comment by SondreNjaastad** [comment]
Try passing the number 15.0

**Comment by cathiele** [comment]
How?

I Just call vehicle.status({refresh: false});

**Comment by SondreNjaastad** [comment]
Oh, sorry. I thought you where starting the AC. I think there has been a modification i have missed. Then this is a bug

**Comment by Hacksore** [comment]
I think I introduced this with the change to how we return the temp based on #51. I think I was a bit YOLO and didn't get to test the change fully as it was EU based.

@SondreNjaastad Could you post a raw status call here? Then I can write a unit test for status calls so we don't run into issues like this in the future :).

**Comment by plips-nl** [comment]
My bad i think. I send the feature request and wrote that part in Util.TS, as a reverse function of the original version. 00H and 01H must be added to util.ts i suppose.

**Comment by Hacksore** [comment]
@plips-nl I think respectively we can agree on the following then?
`00H` => `14.0`
`01H` => `14.5`

**Comment by cathiele** [comment]
Thank you for the fast fix!
