### ISSUE TITLE
feature request: add EVBatteryCharge to output

### ISSUE THREAD

**Issue by plips-nl** [Hacksore/bluelinky#56]
pls add as line 216 in european.vehicle.ts

 EVBatteryCharge: vehicleStatus?.evStatus?.batteryStatus,

**Comment by Hacksore** [comment]
What is the difference between `battery.batSoc` and `evStatus.batteryStatus`?

**Comment by plips-nl** [comment]
batsoc = state of charge of 12V battery, exists in EV’s and in ICE 
evStatus.batteryStatus = state of charge of High Voltage EV battery (like the petrol tank in an ICE)

groet,

Peter

**Comment by Hacksore** [comment]
So I've been looking at this and we need to come up with a good naming to discern the two.

@plips-nl @SondreNjaastad Do you have any suggestions, feel free to make drop something on the sheet we have started below.

https://docs.google.com/spreadsheets/d/1MWLO5rsJROlbWLl0YiQraUsOgIq5ciEhlZ3k4H_RO8M/edit?usp=sharing

**Comment by rhuss** [comment]
I would use `chargeLevel` for the high voltage battery and maybe `boardBatteryChargeLevel` for the 12V board battery (as this information is of much less interest as the charging state of the main battery). If backwards compapility is required you can still keep `batteryCharge` for the 12V battery (but I like to add that `Level` as this points to the unit of this metrics)

**Comment by plips-nl** [comment]
I see you implemented it in development branch. Tested on european vehicle and works fine.

**Comment by Hacksore** [comment]
Fixed with #67
