### ISSUE TITLE
No vehicles detected with Hyundai Kona 2020

### ISSUE THREAD

**Issue by joepv** [Hacksore/bluelinky#58]
The brand new 2020 Hyundai Kona with BlueLink app is not working with bluelinky. The official app works perfectly. Can someone help me?

When I try to get the vehicle information with below code I only got:

```
[2020-07-25 21:38:50] info: {
  "test": 1
}
```

```
const client = new BlueLinky({
		username: 'account@gmail.com',
		password: 'pwd',
		region: 'EU',
		pin: '0000',
	});

	client.on('ready', async () => {
		console.log('am I getting here?');
		const vehicle = await client.getVehicles();
		console.log(vehicles);
	});
```

**Comment by antonyoneill** [comment]
My guess is that you have an authentication issue rather than a vehicle listing issue..

I literally just now integrated this into a mqtt system and had no problems. See https://github.com/antonyoneill/bluelinky-mqtt-ha

My advice is to set `autoLogin` to false in the constructor parameters, then check the return of `client.login()`.

**Comment by joepv** [comment]
Thank you for your help, I set `autoLogin` to `false` and got:

```
[2020-07-26 06:30:50] info: {
  "test": 1
}
Promise { <pending> }
```

with code: 
```
const client = new BlueLinky({
  username: 'account@gmail.com',
  password: 'pwd',
  region: 'EU',
  pin: '0000',
});

const joep = client.login();
console.log(joep);
```

(note, I'm a nodejs newbie, I want to implement this in Node-RED, it didn't work, so I try to figure it out at the source 😊)

**Comment by antonyoneill** [comment]
No problem, looks like we're one step closer to understanding why you can't authenticate.

The return value of `client.login()` is a `Promise<string>` which is an asynchronous construct - the output above says that it is pending, so essentially the output happens before the login function has finished the logic.

There are two ways to wait for the result, one using the `await` keyword within an `async` function (like in your OP) - that would require wrapping everything up in a function. The other is a slightly easier way by using the `then` function on the Promise.

Try
```javascript
const client = new BlueLinky({
  username: 'account@gmail.com',
  password: 'pwd',
  region: 'EU',
  pin: '0000',
});

client.login().then((result) => {
  console.log(result);
});
```

With a bad username or password, I get the following output
```
[2020-07-26 10:09:33] info: {
  "test": 1
}
Response code 400 (Bad Request)
```
When the region, or PIN are wrong, the client throws an exception - which I think is correct.

Let's see what you get back, I think there's an issue here with the library not handling bad username/password correctly - did you double check your credentials? (I couldn't remember what I set mine to so I reset them in the Bluelink app before hand)

**Comment by joepv** [comment]
Thank you very much for your help! I really appreciate it. 

I changed the password and still got a response code `400`. After 15 minutes I tried again and got:

```
[2020-07-26 18:25:20] info: {
  "test": 1
}
Login success
```

Very nice!

Now I try to get the car status:

```
const client = new BlueLinky({
  username: 'account@gmail.com',
  password: 'pwd',
  region: 'EU',
  pin: '0000',
});

client.on('ready', async () => {
          const vehicle = client.getVehicle('XXXXXX');
          const response = await vehicle.status();
          console.log(response);
});
```

and I got:

````
[2020-07-26 18:30:35] info: {
  "test": 1
}
(node:2923) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'parsed' of undefined
    at e.<anonymous> (/home/joep/node_modules/bluelinky/dist/index.js:1:20805)
    at /home/joep/node_modules/bluelinky/dist/index.js:1:2098
    at Object.next (/home/joep/node_modules/bluelinky/dist/index.js:1:2203)
    at n (/home/joep/node_modules/bluelinky/dist/index.js:1:936)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2923) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2923) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The `VIN` is correct, I checked it on the `car` and logged in with in in the app.

Another code error? 
I'm also going to read your guides. Thank you.

**Comment by joepv** [comment]
I got data with this code, but I don't get the status. 

```
client.on('ready', async () => {
	  const vehicle = client.getVehicles('XXXXXX');
	  const response = await vehicle;
	  console.log(response);
});
```

So the issue is solved. I appreciate if you help me with the code to get the status (battery) for the car. 
If you don't have time you can close this issue, because it is solved for me.

**Comment by antonyoneill** [comment]
Great! Glad you got the authentication working.

As for the status, it's a little tricky as the documentation for the project isn't quite up to date. You need to pass in an object and specify whether you want it parsed, or not. I opt for not parsed - see below for an example. My car is an EV so I get the status of the EV battery and 12v battery.

https://github.com/antonyoneill/bluelinky-mqtt-ha/blob/master/index.ts#L22-L33

```javascript
    const status = await vehicle.status({ parsed: false, refresh: true });

    await mqttClient.publish(
      "kona/status",
      JSON.stringify({
        battery: status.evStatus.batteryStatus,
        charging: status.evStatus.batteryCharge,
        'battery-12v': status.battery.batSoc,
        range: status.evStatus.reservChargeInfos.targetSOClist[0].dte.rangeByFuel.totalAvailableRange.value,
        locked: status.doorLock
      })
    );
```

**Comment by joepv** [comment]
Thank you @antonyoneill, you are my hero 🦸‍♂️
It is working now.
If you have sample pieces of code I will document it for your project. No problem. Then I contact you personally on the e-mail provided on GitHub.

**Comment by Hacksore** [comment]
@antonyoneill I really appreciate you helping out with the troubleshooting here.
