### ISSUE TITLE
Cannot read property 'drvDistance' of undefined for non-EV vehicles.

### ISSUE THREAD

**Issue by gruijter** [Hacksore/bluelinky#63]
When requesting the vehicle.status({parsed: false}) for a non-EV vehicle, an error is thrown `Cannot read property 'drvDistance' of undefined`

Can you please make it that 'missing' parameters, like `evStatus`, do not cause a crash when requesting the non-parsed status?

Thx!

**Comment by plips-nl** [comment]
Is the Issue in line 213 of european vehicle:
        range: vehicleStatus.evStatus.drvDistance[0].rangeByFuel.totalAvailableRange.value, whereas line 212, containing an evstatus too has evStatus? . Is that ? for an optional variable?

**Comment by gruijter** [comment]
Another issue is in line 258 of european vehicle.ts. If you change

`const data = response.body.resMsg.gpsDetail`
to
`const data = response.body.resMsg.gpsDetail` || response.body.resMsg`

it will also work for non-EV vehicles.

**Comment by Hacksore** [comment]
Someone should give 556dc273f88bf21a031e176fa6b16cf167ead8e6 a test and see if it resolves this issue.

**Comment by Hacksore** [comment]
Shoudl be fixed with #67
