### ISSUE TITLE
Support for gen 1 vehicles

### ISSUE THREAD

**Issue by aleGuardiola** [Hacksore/bluelinky#7]
{ result:
   { errorSubCode: 'GEN',
     functionName: 'remoteDoorUnLock',
     errorSubMessage:
      'We encountered an error retrieving the vehicle details: nadid',
     errorMessage:
      'We encountered an error retrieving your vehicle information. Please try again later or contact the call center.',
     errorCode: 502 },
  status: 'E:Failure',
  errorMessage: 'Bad Gateway' }

I always get this error, my BlueLink app works correclty so I am n ot sure why I am getting this, any ideas?

**Comment by Hacksore** [comment]
@aleGuardiola Can you provide more detail on how that error is coming back?

**Comment by aleGuardiola** [comment]
I did everything and then i tried to call unlock(), status() give me the same error as well. I did notice that for my car in the hyundai page it includes the vin in the form data and it put the gen as 1. My car is a 2015 genesis coupe, maybe it works different for that year.

**Comment by Hacksore** [comment]
@aleGuardiola could you please provide an example of a request invoked by the web portal (strip/redact anything personal)? My guess is with gen 1 vehicles the request slightly differs in the data like you mentioned.

**Comment by aleGuardiola** [comment]
Request is sent to: https://owners.hyundaiusa.com/bin/common/remoteAction

It includes cookies but i dont think that the api cares about that cuz I suppose the mobile app use the same api without sending the cookie

form data:
vin: {vin of the car}
username: {my email}
token: {the big token}
pin: [the pin]
url: https://owners.hyundaiusa.com/us/en/page/blue-link.html
gen: 1
regId: {this is a combination between one wird string and the vin}
service: remoteunlock

**Comment by aleGuardiola** [comment]
I am trying to figure out how they know what gen is the car, I modified your code for status() with gen one and I added the vin in the form data and I get this error:
{ E_IFRESULT: 'E:Failure',
  E_IFFAILMSG: 'Authorization Required',
  RESPONSE_STRING:
   { errorSubCode: 'IDM_401_4',
     functionName: 'remoteVehicleStatus',
     errorSubMessage: 'Feature disabled as it is not part of subscription.',
     errorMessage: 'Feature disabled as it is not part of subscription.',
     errorCode: 401 } }
