### ISSUE TITLE
Failed requests for American car

### ISSUE THREAD

**Issue by earlwilson** [Hacksore/bluelinky#74]
It appears that some of the methods for the AmericanVehicle class do not work properly. Upon castling start, lock and a few other methods the call results in either a 400 or 503 Bad Gateway error.
However, the odometer call works successfully for me. 

I took a look at the class and it looks like the request urls are being built in different ways, also outputting the Error object shows that the urls are malformed. For instance i see that some of the urls have BASEURL prepended while some don’t. 

Is this bug result of some sort of refactoring?

**Comment by Hacksore** [comment]
@earlwilson I've just published `v5.2.1` see if that still has any issues.

**Comment by Hacksore** [comment]
@earlwilson let me know if this didn't fix the issue and we can continue debugging.
