### ISSUE TITLE
Got always 'Response code 400 (Bad Request)'

### ISSUE THREAD

**Issue by MarkusKress** [Hacksore/bluelinky#76]
Hello,
I tried to connect to the hyundai server, but got constanly an error. I'm not a good programmer. I put the code below in a bl.js file and run it with `node bl.js`
```
const BlueLinky = require('bluelinky');
const client = new BlueLinky({
 username: 'mail@xxx.de',
 password: 'xyxyxxy',
 region: 'EU',
 pin: '1234',
 autologin: true,
 deviceuuid: 'x'
});
```
This is the output:
```
(node:30736) UnhandledPromiseRejectionWarning: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Response code 400 (Bad Request)')
    at t.emit (events.js:187:17)
    at t.<anonymous> (/root/node_modules/bluelinky/dist/index.js:2:41022)
    at /root/node_modules/bluelinky/dist/index.js:2:1955
    at Object.throw (/root/node_modules/bluelinky/dist/index.js:2:2060)
    at a (/root/node_modules/bluelinky/dist/index.js:2:850)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:30736) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30736) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
What I'm doing wrong (I've tested also 'autoLogin' and 'deviceUuid' instead of autologin'/deviceuuid') ? What is the deviceuuid/deviceUuid for?

**Comment by plips-nl** [comment]
What if you retry with
autoLogin
deviceUuid
(capitals)

**Comment by MarkusKress** [comment]
I tried also lowercase for autoLogin/deviceUuid before (but forget to change it back in my posting), but I got exacly the same message. I found a mistake in the documentation (api-reference), where Bluelinky() is also lowercase instead of BlueLinky(), so I tried to change lower and uppercase also for autoLogin/deviceUuid.

**Comment by plips-nl** [comment]
Look in the Bluelinky app if you dont have to change your password or pin.

**Comment by MarkusKress** [comment]
PIN and Password are correct (I have a dot '.' in the password). I've checked this twice with logoff/login in bluelink android app. I'm sure, that user/password/pin are correct. But I'm not sure, if I have to set deviceUuid and which value I have to use for this. I've tried to add vin and vehicleId. 'vin' is clear, for vehicleId I'm using 'OS EV CZECH 20' which is used in the bluelink app.

'''
const client = new BlueLinky({
 username: 'mXXXX@XXXXX.de',
 password: 'BLXXXX.',
 region: 'EU',
 pin: 'XXXX',
 autoLogin: false,
 deviceUuid: 'bluelinky',
 vin: 'TXXXXXXXXXXXXX3',
 vehicleId: 'OS EV CZECH 20'
});
client.login();
'''

**Comment by MarkusKress** [comment]
I've tried also this one with the same error:
```
const client = new BlueLinky({
 username: 'mXXXX@XXXXX.de',
 password: 'BXXXXX.',
 region: 'EU',
 autoLogin: true,
 pin: 'XXXX',
 deviceUuid: 'dxxxxxx9-3xxx5-4xxx-9xxf-cxxxxxxxxxe'
});
```

**Comment by Hacksore** [comment]
@MarkusKress The documentation is quite outdated and some properties are not needed but here are my suggestions.

Try running with the `LOG_LEVEL=debug` so that we can see all the debug logs (might need to mask sensitive data).
```js
const client = new BlueLinky({
 username: 'mXXXX@XXXXX.de',
 password: 'BXXXXX.',
 region: 'EU',
 pin: 'XXXX',
}); 
```

Another option is to double-check that you can log in via the link and you are not getting forced to take some action like changing the password.
https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/oauth2/authorize?response_type=code&state=test&client_id=6d477c38-3ca4-4cf3-9557-2a1929a94654&redirect_uri=https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/oauth2/redirect

**Comment by MarkusKress** [comment]
I've already tried LOG_LEVEL=debug, but did not get more information. Here the output:
```
LOG_LEVEL=debug node bl.js 
[2020-10-19 15:24:59] debug: EU Controller created
[2020-10-19 15:24:59] debug: Bluelinky is logging in automatically, to disable use autoLogin: false
[2020-10-19 15:24:59] debug: loggin into to API
(node:24581) UnhandledPromiseRejectionWarning: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Response code 400 (Bad Request)')
    at t.emit (events.js:187:17)
    at t.<anonymous> (/root/node_modules/bluelinky/dist/index.js:2:41022)
    at /root/node_modules/bluelinky/dist/index.js:2:1955
    at Object.throw (/root/node_modules/bluelinky/dist/index.js:2:2060)
    at a (/root/node_modules/bluelinky/dist/index.js:2:850)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:24581) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24581) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I tried the given URL and saw the Login Screen. I tried to login with my credentials, but then I was redirected to complete empty page. The URL was: 
https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/oauth2/redirect?code=9XLAMNRPMSQXIBRL9AUQJA&state=test
I tried your URL on Deskop and Mobile. Both the same.

**Comment by Hacksore** [comment]
So I added some debug statements and I am seeing the error too. Seems related to fetching the cookies at the initial request so something on the API side could have changed.

![image](https://user-images.githubusercontent.com/996134/96463577-794d5f80-11ec-11eb-9733-c403e604226a.png)

**Comment by MarkusKress** [comment]
Thank you. But how can I test this. Will be a new version (>5.2.1) availibe?

**Comment by faheem3** [comment]
hey guys, if i rent a hyundai to test this out, is it possible?

**Comment by MarkusKress** [comment]
You have to connect the car (using VIN) with your hyundai account for testing.

**Comment by faheem3** [comment]
im guessing the hyundai account w/ that vin will already be made. if not then should be ok....i want to try out this api and need a hyundai. any suggestions?

**Comment by MarkusKress** [comment]
I would test it, I have a Hyundai EV car for Region EU. But I have no experience about npm packages, only a little bit js programming. So I'm more a less only a user.

**Comment by PierreLevres** [comment]
Markus, first you'd have to install npm and node.js on your machine, lots of how-to's to find around.
Then install bluelinky (npm install bluelinky)
Then create a config file (config.json) with your client definition
Then run the debug program (node debug.js)

**Comment by MarkusKress** [comment]
I have npm and node.js already installed. I did also an 'npm install bluelinky'.
But I did not understand about config.json. What must be inside the file and where must be located? 
I found the installed bluelinky and debug.js in /root/node_modules/bluelinky

**Comment by Hacksore** [comment]
@MarkusKress I will publish the latest fix and it should resolve this issue.

**Comment by MarkusKress** [comment]
Thanks. I've updated to 5.2.2 and it works.

**Comment by Hacksore** [comment]
@MarkusKress since this fixed the issue I'll close this. 

As for the status you need to pass in an object now to status, like `.status({ parsed: false })` however it should not be erroring. I'll take a look and see if this is a bug.

**Comment by MarkusKress** [comment]
start() and update() also does not work.

**Comment by Hacksore** [comment]
@MarkusKress update is not a thing anymore. As for the start command please open a new issue if you found a bug.

**Comment by MarkusKress** [comment]
Did you plan to solve also update(), start() ...?

**Comment by MarkusKress** [comment]
Sorry, didn't catch about update.
