### ISSUE TITLE
Daily Remote Service Request Limit?

### ISSUE THREAD

**Issue by chasenicholl** [Hacksore/bluelinky#80]
[Update] Bringing to the top. Spoke with Blue Link US support and...

- 10 requests per action type a day. i.e. The lock() method will only work 10 times a "day".
- 30 requests overall per day. i.e. If I called status() 25 times, then I could only call lock() 5 times before being blocked.

----

Hi!

I started developing a plugin using your wonderful library today! Thanks so much for the work creating a wrapper around this API!

However, I ran into, rather quickly an API error on the `Vehicle.status` method, https://github.com/Hacksore/bluelinky/blob/master/lib/vehicles/american.vehicle.ts#L167. 

I was polling the endpoint once every 10 seconds, and _maybe_ queried it 100 times maximum, if that.

```json
{
    "errorSubCode": "HT_534",
    "systemName": "HATA",
    "functionName": "remoteVehicleStatus",
    "errorSubMessage": "HATA remoteVehicleStatus service failed while performing the operation RemoteVehicleStatus",
    "errorMessage": "You have exceeded the daily remote service request limit. Your last request was not processed.",
    "errorCode": 502,
    "serviceName": "RemoteVehicleStatus"
}
```
----

A questions? And an Idea.

- Whats the maximum daily request limit? I can't seem to find that documented anywhere.
- The promise doesn't throw an exception on non `200` response codes, ideally this would raise an exception instead of having to add `console.log` statements to the compiled JS.

**Comment by SondreNjaastad** [comment]
Errorhandling is definetly something that we can improve.
I'm not sure about the american max limit, as we dont have the same limit in Europe, @Hacksore might know more about that.
Maybe its an idea to indicate this limit somewhere in code.

we are working to keep this library the same for EU, US and Canada, so there might be region spesific diffrences that are not documented.

We will take your suggestions into account for future development

**Comment by chasenicholl** [comment]
@SondreNjaastad Thanks for the reply! I'll test the API limits for the US today and report back with the total number of requests I was able to make for you all. 

If I were to make a suggestion a static member to each vehicle class with its rate limit might be a nice approach that way someone, like say myself could keep track of how many times I hit the API against the known limit.

Thanks!

**Comment by chasenicholl** [comment]
@Hacksore @SondreNjaastad I just got off the phone with Hyundai Blue Link US support, and the limits are ridiculously low. [facepalm]

- 10 requests per action type a day. i.e. The `lock()` method will only work 10 times a "day".
- 30 requests overall per day. i.e. If I called `status()` 25 times, then I could only call `lock()` 5 times before being blocked.

Pretty ridiculous, as these limits are imposed on the Blue Link app itself as well. The very friendly support agent did say they receive LOTS of complaints about this, think real estate agents who are actually getting in and out of their car a lot all day, and then the Blue Link app itself stops working... And that she's heard chatter of raising them, but again could not confirm.

Your reverse engineered library is wonderful!  However, I'm going to reach out to SmartCar.com and see if they brokered a deal with Hyundai in which their API integration has a higher limit, or uses a different integration point in the backend.

For context. I developed, and was about to make public, a Homebridge Plugin that lets you unlock / lock your car as well as monitor battery charge progress in Apple Home / Siri. Works wonderfully, until hitting these hilariously low request limits!

Thanks again for your work. I'll let you know where I net out.

**Comment by Hacksore** [comment]
@chasenicholl Thank you for raising this issue and contributing your valuable feedback. 

Seems like such a ridiculous thing to have these limitations on calls to their API. So two things come to mind that can help this library out.

- [Documentation on limits](https://github.com/Hacksore/bluelinky/wiki/API-Rate-Limits)
- Proper error handling when hitting limits

**Comment by chasenicholl** [comment]
@Hacksore I'm not sure what your contribution rules are. But I plan on submitting a PR which would update the American API endpoints. As I'd like to take advantage of this upstream affect in my Homebridge Plugin, without rolling my own API Client.

By using Charles Proxy to intercept the requests to control Hyundai via their website two things became evident.

1. There is another API!!! `https://owners.hyundaiusa.com/bin/common/{SERVICE}` with the same Request and Response structure as the one this unofficial SDK uses.

2. This API **DOES NOT HAVE ANY REQUEST LIMITS**!!! Woohoo. I pulled my cars status, unlocked, locked, started, stopped hundreds of times over the last few days.

**Comment by Hacksore** [comment]
@chasenicholl 

Well if we want to switch back to the web API for the US we just need to have the location command still hitting the app endpoint (not available via web).

I'm ok with going back to the web API but will require a good deal of testing all the endpoints.

Submit a PR to `develop` and I can review the changes and help test it out.

**Comment by truedays** [comment]
@chasenicholl can you submit a PR with the "new" API used? It's not clear to me where I can try to plug this in--probably made more difficult because ./default/index.js is minified. 

@Hacksore, Are there any docs on any findings that elaborate on the difference between the App and Web API end-points ?

is `api.telematics.hyundaiusa.com` the "App" end-point?
and
> owners.hyundaiusa.com/bin/common/{SERVICE}

the Web end-point (re)discovered by @chasenicholl ?

**Comment by Hacksore** [comment]
@truedays there are not really any docs but if you look at this older version you can get an idea at least for the US API. You are also right `api.telematics.hyundaiusa.com` is the app and `owners.hyundaiusa.com/bin/common/{SERVICE}` is for the web app.

https://github.com/Hacksore/bluelinky/blob/d5a70c5c27637f784b5131143c2b2442e3f791f8/lib/constants.ts

**Comment by Hacksore** [comment]
For now, let's use the table below as a point of reference for API rate limits. 

If someone wants to submit a PR to start using the web API again for the US I'd most likely approve it as long as we still use the app API to get vehicle status as it's not available on the web for some reason.

https://github.com/Hacksore/bluelinky/wiki/API-Rate-Limits

It was also mentioned in this thread better handling of rate limits to dispatch proper errors to the user. So anyone willing to take on that effort would be appreciated 😁.
