### ISSUE TITLE
@EuropeControllerLogin: AuthCode was not found

### ISSUE THREAD

**Issue by samsmooth** [Hacksore/bluelinky#81]
Since some days I'm not able to get data anymore. Any changes in the service?

`(node:10558) UnhandledPromiseRejectionWarning: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('@EuropeControllerLogin: AuthCode was not found')
    at t.emit (events.js:182:17)
    at t.<anonymous> (/opt/fhem/node_modules/bluelinky/dist/index.js:2:41053)
    at /opt/fhem/node_modules/bluelinky/dist/index.js:2:1955
    at Object.throw (/opt/fhem/node_modules/bluelinky/dist/index.js:2:2060)
    at a (/opt/fhem/node_modules/bluelinky/dist/index.js:2:850)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:10558) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10558) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by PierreLevres** [comment]
Try to logout and login again from the app on your phone. It might need a change of password.

**Comment by samsmooth** [comment]
Thank you, Pierre. That's it.
