### ISSUE TITLE
Hyundai Kona eletric range always zero (0)

### ISSUE THREAD

**Issue by mpucherSmIT** [Hacksore/bluelinky#82]
Hi, I own a czech 2020 Kona eletric and like bluelinky so far!

In status->evStatus->driveDistance->rangeByFuel->evModeRange is always 0:

{
  rangeByFuel: {
    evModeRange: { value: **0**, unit: 1 },
    totalAvailableRange: { value: **0**, unit: 1 }
  },
  type: 2
}

Is it possible to get the calculated remaining range from the vehicle? The bluelink app displays the value. Does it calculate it on it's own?

node version: 6.14.8
bluelinky version: 5.2.2

Thank you!

**Comment by PierreLevres** [comment]
That is strange, it ought to work. Could you send the version numbers of the systems in your car?
Do you get normal odometer output?

**Comment by mpucherSmIT** [comment]
![IMG_20201113_111124](https://user-images.githubusercontent.com/38916244/99061183-74888b00-25a1-11eb-8abb-04c36b40c2a4.jpg)

What do you mean by odometer output? I can read the correct GPS coordinates, the battery SoC and other values.

Thank you!

**Comment by SondreNjaastad** [comment]
I got the same issue. I'll try to look into it. Ioniq EV 2020

**Comment by mpucherSmIT** [comment]
> ~I got the same issue. I'll try to look into it. Ioniq EV 2020~
> 
> Got data right after posting this comment, i'll keep an eye out to see if it dropd to 0 again

could you please post your code how you select the value?

**Comment by Hacksore** [comment]
Do we think this is a bug with the library or actually the service API layer from Hyundai?

**Comment by mpucherSmIT** [comment]
I think the issue can be closed. As we all know, the hyundai API/backend is very unstable, the values appeared today. And I really changed nothing:

{
  rangeByFuel: {
    evModeRange: { value: **107**, unit: 1 },
    totalAvailableRange: { value: **107**, unit: 1 }
  },
  type: 2
}

One thing I'm not sure is at the moment of ready that values the car is plugged in and charging. Will try later when the plug is removed...
