### ISSUE TITLE
Support for bluelink (autolink) straya

### ISSUE THREAD

**Issue by Hacksore** [Hacksore/bluelinky#9]
@Technoash can you help an m9 out and find, someone, to help here?

https://www.myhyundai.com.au/

**Comment by Technoash** [comment]
Yeah, how is bluelink different in Australia though?

**Comment by Hacksore** [comment]
@Technoash The US vs Canada is vastly different so I am suspecting the same is true for Australia as well. 

You can peak at this branch and get an idea of what I mean.
[support-canada-api](https://github.com/Hacksore/bluelinky/tree/support-canada-api)

**Comment by altagir** [comment]
- open your site https://www.myhyundai.com.au/
- right click , inspect (on chrome)
- go to tab Network
- login / do a lock / unlock / start / refresh or any function needed
- look for a down arrow in inspector : export HAR
- edit the file, look for password, email and remove them from file.
- post it it here or send email to Sean

**Comment by Hacksore** [comment]
@altagir i think the problem is Ashneil doesn’t have a Hyundai with bluelink 🙃. I was seeing if he could do some asking around and find someone who does have it.

**Comment by Technoash** [comment]
I'll keep an eye out for someone with a a Hyundai and bluelink. Hyundai's
aren't that common here - at least not with people I know.

**Comment by altagir** [comment]
added a [post to Australian EV forum](https://forums.aeva.asn.au/viewtopic.php?f=63&t=6317)

**Comment by Hacksore** [comment]
Based on the comments from the EV forum I think we can close this for now.

**Comment by Hacksore** [comment]
So for what it's worth I think this is possible to support but would be based on demand.

https://apkpure.com/hyundai-auto-link-premium/com.hyundai.autolink.premium

**Comment by stibbzy** [comment]
Hi Hacksore. I’ve just got my Australian Ioniq and would be very keen on some API interface to the Autolink module. Mine is the Premium module, which includes 4G SIM connectivity, if that makes a difference. I’m happy to help out any way I can, if you were keen to try.

**Comment by Hacksore** [comment]
@stibbzy can you confirm what the latest version of the app is? 

Also, are you able to login to this web portal?
https://www.myhyundai.com.au/

**Comment by stibbzy** [comment]
Hi @Hacksore 
According to the App Store, the current version of 'Hyundai Auto Link Premium' is 1.2.4. I can also confirm I can log into the portal using my account details. To be clear, I'm actually not getting the OBD module installed until Wednesday, so I may not be of much help until then!

**Comment by Hacksore** [comment]
@stibbzy let us know if we want to revisit this in the future. Going to close it out for now.

**Comment by stibbzy** [comment]
@Hacksore Sorry mate, I should have let you know that I now have the Autolonk module installed and operational!

Happy to open the issue and assist in any way I can. Cheers.

**Comment by Hacksore** [comment]
@stibbzy If you wanna share the APK as the latest is not on APKPure and it's not available in my country.

https://apkpure.com/hyundai-auto-link/com.hyundai.autolink

**Comment by stibbzy** [comment]
Hi @Hacksore 
I use iOS, so I’m not familiar with APKs. I’ll have a look around and see what I can find.

**Comment by takenalias** [comment]
Hey guys. I am an Android user, I have a 2019 i30 nline with Auto link premium. Let me know how I can help.  I'll try get the APK tomorrow.

**Comment by takenalias** [comment]
@Hacksore here is the latest apk. https://drive.google.com/file/d/1XamXTWmOruspU5PdmH5MzTFhq7uJEwBk/view?usp=sharing

There is 2fa on the app. I feel like this will be the biggest hurdle. I'd be super keen to get something working though.

**Comment by rarrr** [comment]
I've just got a car with the Auto Link.
I've defeated the cert pinning on the app but it looks like the data to the servers is encrypted, well beyond my knowledge.  I've blanked out some data because this is captured from the login process.
![image](https://user-images.githubusercontent.com/7687585/143681937-93369dbd-a2fe-470e-af95-a9b0f5d238e3.png)

**Comment by Hacksore** [comment]
@rarrr So I guess they have the messages encrypted with a public key the client has and the server decrypts them with the private key?

It is possible to understand how the encryption process works client-side and we'd just have to send encrypted payloads.

Can you at least start sharing the endpoints you have been interacting with here?

**Comment by rarrr** [comment]
Here are some.
https://autolinkapi-premium.hmca.com.au/api/app/user/login
https://api.myhyundai.com.au/autolinkservice.asmx?op=AuthenticateUser
https://autolinkapi-premium.hmca.com.au/api/app/user/login
https://autolinkapi-premium.hmca.com.au/api/app/Setting/view
https://autolinkapi-premium.hmca.com.au/api/app/Message/noticeNewCount
https://autolinkapi-premium.hmca.com.au/api/app/DrivingHistory/get
https://autolinkapi-premium.hmca.com.au/api/app/weather/hour
https://autolinkapi-premium.hmca.com.au/api/app/weather/day
https://gds.hyundai-motor.com/autolink-premium/updateif.aspx

I also decompiled the apk and found these, my understanding of Java is none existent but it might be helpful for someone.

[SEEDencrypt.txt](https://github.com/Hacksore/bluelinky/files/7612439/SEEDencrypt.txt)
[KISA_SEED_CBC.txt](https://github.com/Hacksore/bluelinky/files/7612440/KISA_SEED_CBC.txt)
[PremiumRequest.txt](https://github.com/Hacksore/bluelinky/files/7612441/PremiumRequest.txt)

**Comment by stibbzy** [comment]
Any further progress on this? I’d love this integration to work with my Aussie Ioniq!

**Comment by Neddii** [comment]
Hello! I’ve recently gotten a 2024 Hyundai Kona and I use the Bluelink app, so it looks like they may have updated from AutoLink. 
I’m very keen to help you with this, but I only have a very basic tech knowledge (very basic)
If there’s anything I can do to help please let me know what to do. Otherwise hopefully someone who knows what they’re talking about will see this and jump in 😂

**Comment by stibbzy** [comment]
Unfortunately I’ve moved on to a Tesla M3, so I can’t provide any help :(
