### ISSUE TITLE
lock/unlock not working - American Vehicles

### ISSUE THREAD

**Issue by loslobosggb** [Hacksore/bluelinky#90]
When trying to do lock via  "/ac/v2/rcs/rdo/off", get the response below in figure 1.  When doing the lock command via MyHundai android app, it works without issue.  Perhaps there's another api call to do unlock?

Figure 1.
{
    "errorSubCode": "GEN",
    "systemName": "HATA",
    "functionName": "remoteDoorLock",
    "errorSubMessage": "HATA remoteDoorLock service failed while performing the operation RemoteDoorLock",
    "errorMessage": "We're sorry, but we could not complete your request. Please try again later.",
    "errorCode": 502,
    "serviceName": "RemoteDoorLock"
}

**Comment by Hacksore** [comment]
HI @loslobosggb, Are you using bluelinky or trying to create a request on your own? There is another API endpoint that can be seen in older versions of the lib.

https://github.com/Hacksore/bluelinky/blob/d5a70c5c27637f784b5131143c2b2442e3f791f8/lib/vehicle.ts#L73

**Comment by loslobosggb** [comment]
Create one of my own.  I'd like to make this available in a c# .net core
solution.  Thanks.  I'll see if these work.

**Comment by loslobosggb** [comment]
The other API endpoint works for lock and a number of other features, such as start.  I was able see the functionality mentioned in the old lib when sending commands via the myhundai website as well.  
Thanks.

**Comment by SondreNjaastad** [comment]
@loslobosggb Do you have a public repository for the C# lib? I'm a lot more experienced in C# than JS/TS, so i might be able to contribute

**Comment by loslobosggb** [comment]
Not at the moment.  I can when done.  I'm working on this so I can
integrate my car into my home automation system.  The idea is to issue a
single command to amazon echo that'll lock the car, open the garage door,
start the car so it warms up.  A safeguard will make sure it will only do
it if the car is home.

I'll make the Hyundai stuff a separate project so anyone can use it and
publish when done.  Currently I'm using a combination of the 2 hyundai API
as the web based one doesn't seem to be able to query for cars or provide
the regId based on what I've seen so far.

**Comment by SondreNjaastad** [comment]
Are you taking the different regions into Account? Using interfaces like we have done in Bluelinky?

**Comment by Hacksore** [comment]
@loslobosggb What are you planning for car detection? I was working on this a while back but for now have abandoned the project as the hardware I have is shit lol.

https://github.com/Hacksore/garage-plate-detection

**Comment by loslobosggb** [comment]
I'm going to do it based on the location.  A part of the hyundai api
provides the vehicles long/lat.  I'll use that to determine if the vehicle
is at home.
