### ISSUE TITLE
Setting Charge Limit

### ISSUE THREAD

**Issue by nickb512** [Hacksore/bluelinky#92]
Hi Folks

Does anyone know if it's possible to set the charge limit through the API? Can't see anything documented but maybe someone knows something I don't? I presume it's possible through the API as it can be done via the app, but maybe not implemented in Bluelinky yet?

Ta

**Comment by PierreLevres** [comment]
Not yet. I implemented it in my eu-python lib. So should be easy to port.  But don’t know about ca and us.

**Comment by nickb512** [comment]
@PierreLevres ngl I'm actually an EU Kia e-Niro owner so am using your kuvork nodered palette but was thinking there was more chance of it having been implemented in the bluelinky repo but I guess not. I have looked through the code for kuvork but can't spot how to control this. Any tips?

**Comment by PierreLevres** [comment]
I keep kuvork more or less identical to bluelinky. But it is a good improvement so i might work on it sometime soon.

**Comment by altagir** [comment]
For canada  (need vrfypin authentication)

Plugtype 1 is AC, type 0 is DC

GET  :
Request URL: https://mybluelink.ca/tods/api/evc/selsoc

`{"responseHeader":{"responseCode":0,"responseDesc":"Success"},"result":[{"plugType":0,"level":80,"dte":{"rangeByFuel":{"gasModeRange":{"value":0.0,"unit":1},"evModeRange":{"value":177.0,"unit":1},"totalAvailableRange":{"value":177.0,"unit":1}},"type":2}},{"plugType":1,"level":100,"dte":{"rangeByFuel":{"gasModeRange":{"value":0.0,"unit":1},"evModeRange":{"value":177.0,"unit":1},"totalAvailableRange":{"value":177.0,"unit":1}},"type":2}}]}`

SET:
Request URL: https://mybluelink.ca/tods/api/evc/setsoc
**`{"tsoc":[{"plugType":0,"level":80},{"plugType":1,"level":100}],"pin":"1111"}**

{"responseHeader":{"responseCode":0,"responseDesc":"Success"},"result":[{"plugType":0,"level":80,"dte":{"rangeByFuel":{"gasModeRange":{"value":0.0,"unit":1},"evModeRange":{"value":177.0,"unit":1},"totalAvailableRange":{"value":177.0,"unit":1}},"type":2}},{"plugType":1,"level":100,"dte":{"rangeByFuel":{"gasModeRange":{"value":0.0,"unit":1},"evModeRange":{"value":177.0,"unit":1},"totalAvailableRange":{"value":177.0,"unit":1}},"type":2}}]}`

**Comment by Hacksore** [comment]
Since this is quite stale now I'm closing it but would approve a PR that implements it. 

More info about enabling this:
https://github.com/PierreLevres/BlUVO/blob/227a2188ccdf3138318ff7935ef1486b17edc9ce/bluvo_lib.py#L840

**Comment by neoPix** [comment]
I'm working on a EU PR for this.
