### ISSUE TITLE
Improvement for Climate Control

### ISSUE THREAD

**Issue by xerion3800** [Hacksore/bluelinky#98]
In the Bluelink App it is possible to use two diferent Climate Controls. Once with Schedule and the other one for directly climate.
When i use the directly Climate then is the duration time 15 minutes. When i use the Schedule then is the duration time is 30 minutes. In Bluelinky i can "only" use the 15 minutes Mode. Could it be possible to add the Schedule in Bluelinky that i can change the schedule via Smart Home for example? Or is an another possibility to use the 30 Minute Mode?

**Comment by Hacksore** [comment]
@xerion3800 This does not seem to be a feature in the US but I'd love for 30-minute runtime. Furthermore, it might be something that is only available for EV's.

I think for now I will close this as we don't have region parity for this feature but we can continue any discussion nevertheless.

**Comment by xerion3800** [comment]
Yes it is a nice Feature for the EV's. I will have an look on it and maybe later create a new request. For now i hope we can use bluelinky again for the EU
